{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nemo-common.postgresql.fullname" . }}
  labels:
    app.kubernetes.io/component: postgres
    {{- include "nemo-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgresql.auth.password | quote }}
{{- end }}
