{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nemo-common.postgresql.fullname" . }}
  labels:
    app.kubernetes.io/component: postgres
    {{- include "nemo-platform.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.service.port | int }}
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/component: postgres
    {{- include "nemo-platform.selectorLabels" . | nindent 4 }}
{{- end }}
