# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

NMP_CUSTOMIZER_FILE_IO_IMAGE_ENVVAR = "NMP_CUSTOMIZER_FILE_IO_IMAGE"
NMP_CUSTOMIZER_TRAINING_AUTOMODEL_IMAGE_ENVVAR = "NMP_CUSTOMIZER_TRAINING_AUTOMODEL_IMAGE"

FILE_IO_IMAGE = "test-file-io:v1"
TRAINING_AUTOMODEL_IMAGE = "test-training-automodel:v1"
TRAINING_RL_IMAGE = "test-training-rl:v1"
