#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Load generated test dataset into Intake API via HTTP requests.

This script takes the JSON files generated by generate_test_dataset.py and
POSTs them to the Intake API /entries endpoint.

Features:
- Parallel loading with configurable concurrency
- Progress tracking with real-time statistics
- Comprehensive error handling and reporting
- Dry-run mode for validation
- Flexible data directory and URL configuration
- Optional category filtering

Usage:
    python load_test_data.py                    # Load all data to localhost:8080
    python load_test_data.py --dry-run          # Validate without posting
    python load_test_data.py --url https://nemo.example.com --workspace my-team
    python load_test_data.py --categories single_turns conversations  # Load specific categories
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import requests
from requests.adapters import HTTPAdapter

# ---------------------------------------------------------------------------
# HTTP Client Configuration
# ---------------------------------------------------------------------------


def create_http_session(pool_size: int = 10) -> requests.Session:
    """Create HTTP session with retry strategy and a connection pool large enough for concurrent workers."""
    session = requests.Session()

    adapter = HTTPAdapter(max_retries=3, pool_connections=pool_size, pool_maxsize=pool_size)
    session.mount("http://", adapter)
    session.mount("https://", adapter)

    return session


def entries_url(base_url: str, workspace: str) -> str:
    """Build the v2 entries endpoint URL."""
    return f"{base_url.rstrip('/')}/apis/intake/v2/workspaces/{workspace}/entries"


def verify_api_connectivity(post_url: str) -> bool:
    """Verify the entries endpoint is reachable by listing one entry."""
    try:
        response = requests.get(post_url, params={"page": 1, "page_size": 1}, timeout=5)
        if response.status_code == 200:
            print(f"✅ Entries endpoint reachable: {post_url}")
            return True
        print(f"❌ Entries endpoint returned {response.status_code}: {response.text[:200]}")
        return False
    except requests.RequestException as e:
        print(f"❌ Cannot reach entries endpoint at {post_url}: {e}")
        return False


# ---------------------------------------------------------------------------
# Data Loading Functions
# ---------------------------------------------------------------------------


def load_entry_data(data_dir: Path, categories: Optional[List[str]] = None) -> Dict[str, List[Dict[str, Any]]]:
    """
    Load entry data from JSON files.

    Args:
        data_dir: Directory containing JSON files
        categories: Optional list of specific categories to load

    Returns:
        Dictionary mapping category names to entry lists
    """
    if not data_dir.exists():
        raise FileNotFoundError(f"Data directory not found: {data_dir}")

    available_files = {
        "single_turns": data_dir / "single_turns.json",
        "conversations": data_dir / "conversations.json",
        "feedback_heavy": data_dir / "feedback_heavy.json",
        "action_heavy": data_dir / "action_heavy.json",
        "all_entries": data_dir / "all_entries.json",
    }

    # Filter to requested categories
    if categories:
        files_to_load = {cat: available_files[cat] for cat in categories if cat in available_files}
        missing = set(categories) - set(available_files.keys())
        if missing:
            print(f"⚠️  Unknown categories: {missing}")
    else:
        # Load all except the combined file
        files_to_load = {k: v for k, v in available_files.items() if k != "all_entries"}

    dataset = {}
    total_entries = 0

    for category, file_path in files_to_load.items():
        if not file_path.exists():
            print(f"⚠️  File not found: {file_path}")
            continue

        try:
            with open(file_path, "r") as f:
                entries = json.load(f)

            dataset[category] = entries
            total_entries += len(entries)
            print(f"📁 Loaded {len(entries)} entries from {category}")

        except (json.JSONDecodeError, IOError) as e:
            print(f"❌ Error loading {file_path}: {e}")

    print(f"📊 Total entries loaded: {total_entries}")
    return dataset


def post_entry(
    session: requests.Session,
    post_url: str,
    entry: Dict[str, Any],
    dry_run: bool = False,
    timeout: float = 30.0,
) -> Tuple[bool, Optional[str]]:
    """
    POST a single entry to the v2 entries endpoint.

    Args:
        session: HTTP session
        post_url: Full URL of the v2 entries endpoint
        entry: Entry data to post
        dry_run: If True, validate but don't send request
        timeout: Per-request timeout in seconds

    Returns:
        Tuple of (success, error_message)
    """
    if dry_run:
        required_fields = ["data", "context"]
        missing = [field for field in required_fields if field not in entry]
        if missing:
            return False, f"Missing required fields: {missing}"

        request = entry["data"].get("request")
        response = entry["data"].get("response")
        context = entry.get("context")

        if not isinstance(request, dict) or not request.get("model") or not request.get("messages"):
            return False, "Invalid data.request; expected non-empty model and messages"
        if not isinstance(response, dict) or not isinstance(response.get("choices"), list) or not response["choices"]:
            return False, "Invalid data.response; expected non-empty choices"
        first_choice = response["choices"][0]
        message = first_choice.get("message") if isinstance(first_choice, dict) else None
        if not isinstance(message, dict) or "role" not in message:
            return False, "Invalid data.response.choices[0].message"
        if not isinstance(context, dict) or "app" not in context or "task" not in context:
            return False, "Invalid context; expected app and task"
        return True, None

    try:
        response = session.post(
            post_url,
            json=entry,
            headers={"Content-Type": "application/json"},
            timeout=timeout,
        )

        if response.status_code in [200, 201]:
            return True, None
        else:
            return False, f"HTTP {response.status_code}: {response.text[:200]}"

    except requests.RequestException as e:
        return False, f"Request failed: {str(e)[:100]}"


# ---------------------------------------------------------------------------
# Parallel Loading with Progress Tracking
# ---------------------------------------------------------------------------


class LoadingProgress:
    """Track loading progress and statistics."""

    def __init__(self, total_count: int):
        self.total_count = total_count
        self.completed = 0
        self.successful = 0
        self.failed = 0
        self.start_time = time.time()
        self.errors: List[str] = []

    def update(self, success: bool, error: Optional[str] = None) -> None:
        """Update progress counters."""
        self.completed += 1
        if success:
            self.successful += 1
        else:
            self.failed += 1
            if error:
                self.errors.append(error)

    def print_progress(self) -> None:
        """Print current progress to console."""
        elapsed = time.time() - self.start_time
        rate = self.completed / elapsed if elapsed > 0 else 0

        progress_pct = (self.completed / self.total_count) * 100

        print(
            f"\r📈 Progress: {self.completed}/{self.total_count} ({progress_pct:.1f}%) | "
            f"✅ {self.successful} | ❌ {self.failed} | {rate:.1f}/sec",
            end="",
            flush=True,
        )

    def print_summary(self) -> None:
        """Print final loading summary."""
        elapsed = time.time() - self.start_time
        print("\n\n📊 Loading Summary:")
        print(f"   • Total entries: {self.total_count}")
        print(f"   • Successful: {self.successful}")
        print(f"   • Failed: {self.failed}")
        print(f"   • Success rate: {(self.successful / self.total_count) * 100:.1f}%")
        print(f"   • Total time: {elapsed:.1f}s")
        print(f"   • Average rate: {self.total_count / elapsed:.1f} entries/sec")

        if self.errors:
            print("\n❌ Error samples:")
            for error in self.errors[:5]:  # Show first 5 errors
                print(f"   • {error}")
            if len(self.errors) > 5:
                print(f"   • ... and {len(self.errors) - 5} more errors")


def load_dataset_parallel(
    session: requests.Session,
    post_url: str,
    dataset: Dict[str, List[Dict[str, Any]]],
    dry_run: bool = False,
    max_workers: int = 10,
) -> LoadingProgress:
    """
    Load all entries with progress tracking, optionally in parallel.

    Args:
        session: HTTP session (requests.Session is thread-safe for send())
        post_url: Full URL of the v2 entries endpoint
        dataset: Dictionary of categorized entry data
        dry_run: If True, validate but don't send requests
        max_workers: Maximum concurrent requests. 1 runs sequentially.

    Returns:
        LoadingProgress object with final statistics
    """
    all_entries = [entry for entries in dataset.values() for entry in entries]
    if not all_entries:
        raise ValueError("No entries found in the selected dataset")

    progress = LoadingProgress(len(all_entries))

    mode = "dry-run validation" if dry_run else "data loading"
    effective_workers = 1 if dry_run else max(1, max_workers)
    print(f"🚀 Starting {mode} with {effective_workers} worker(s)...")

    def record(success: bool, err: Optional[str]) -> None:
        progress.update(success, err)
        if progress.completed % 10 == 0 or progress.completed == progress.total_count:
            progress.print_progress()

    if effective_workers == 1:
        for entry in all_entries:
            record(*post_entry(session, post_url, entry, dry_run))
    else:
        with ThreadPoolExecutor(max_workers=effective_workers) as executor:
            futures = [executor.submit(post_entry, session, post_url, entry, dry_run) for entry in all_entries]
            for future in as_completed(futures):
                record(*future.result())

    progress.print_summary()

    return progress


# ---------------------------------------------------------------------------
# CLI Interface
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Load test entry data into Intake API",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s                                    # Load all data to localhost
  %(prog)s --dry-run                          # Validate without posting
  %(prog)s --url http://api.example.com:8000  # Load to custom API
  %(prog)s --categories single_turns          # Load only single-turn entries
  %(prog)s --data-dir /path/to/data           # Use custom data directory
  %(prog)s --workers 20                       # Use 20 concurrent workers
        """,
    )

    parser.add_argument(
        "--url",
        default="http://localhost:8080",
        help="Base URL of the NeMo Platform gateway (default: http://localhost:8080)",
    )

    parser.add_argument(
        "--workspace",
        default="default",
        help="Workspace to write entries into (default: default)",
    )

    parser.add_argument(
        "--data-dir",
        type=Path,
        default=Path(__file__).resolve().parents[3] / ".tmp" / "intake" / "test_data",
        help="Directory containing JSON data files (default: <repo>/.tmp/intake/test_data)",
    )

    parser.add_argument(
        "--categories",
        nargs="*",
        choices=["single_turns", "conversations", "feedback_heavy", "action_heavy"],
        help="Specific categories to load (default: all)",
    )

    parser.add_argument(
        "--workers",
        type=int,
        default=3,
        help="Number of concurrent workers (default: 3). Higher values can overwhelm a local intake instance.",
    )

    parser.add_argument("--dry-run", action="store_true", help="Validate data without sending requests")

    return parser.parse_args()


# ---------------------------------------------------------------------------
# Main Function
# ---------------------------------------------------------------------------


def main() -> int:
    """Main loading function."""
    args = parse_args()

    print("🎯 Intake API Data Loader")
    print("=" * 50)
    print(f"API URL: {args.url}")
    print(f"Workspace: {args.workspace}")
    print(f"Data directory: {args.data_dir}")
    print(f"Categories: {args.categories or 'all'}")
    print(f"Workers: {args.workers}")
    print(f"Dry run: {args.dry_run}")
    print()

    try:
        post_url = entries_url(args.url, args.workspace)

        # Verify API connectivity (unless dry run)
        if not args.dry_run:
            if not verify_api_connectivity(post_url):
                return 1

        # Load entry data
        dataset = load_entry_data(args.data_dir, args.categories)
        if not dataset:
            print("❌ No data to load")
            return 1

        # Create HTTP session with a connection pool sized for the worker count
        session = create_http_session(pool_size=max(1, args.workers))

        progress = load_dataset_parallel(
            session=session, post_url=post_url, dataset=dataset, dry_run=args.dry_run, max_workers=args.workers
        )

        # Return appropriate exit code
        if progress.failed == 0:
            print(f"\n✅ {'Validation' if args.dry_run else 'Loading'} completed successfully!")
            return 0
        elif progress.successful > 0:
            print(f"\n⚠️  {'Validation' if args.dry_run else 'Loading'} completed with {progress.failed} errors")
            return 1
        else:
            print(f"\n❌ {'Validation' if args.dry_run else 'Loading'} failed completely")
            return 2

    except KeyboardInterrupt:
        print("\n\n⏹️  Loading interrupted by user")
        return 130
    except Exception as e:
        print(f"\n💥 Unexpected error: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
