{{- if and (include "nemo-platform.authEnabled" .) .Values.envoyProxy.enabled }}
{{- if .Values.envoyProxy.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nmp-envoy.serviceAccountName" . }}
  labels:
    {{- include "nmp-envoy.labels" . | nindent 4 }}
  {{- with .Values.envoyProxy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.envoyProxy.serviceAccount.automount }}
{{- end }}
{{- end }}
