{{- if and (include "nemo-platform.authEnabled" .) .Values.envoyProxy.enabled }}
{{- if .Values.envoyProxy.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "nmp-envoy.servicename" . }}
  labels:
    {{- include "nmp-envoy.labels" . | nindent 4 }}
  {{- with .Values.envoyProxy.autoscaling.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nmp-envoy.servicename" . }}
  minReplicas: {{ .Values.envoyProxy.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.envoyProxy.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.envoyProxy.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.envoyProxy.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.envoyProxy.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.envoyProxy.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
