{{- if and (include "nemo-platform.authEnabled" .) .Values.envoyProxy.enabled }}
{{- if .Values.envoyProxy.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nmp-envoy.servicename" . }}
  labels:
    {{- include "nmp-envoy.labels" . | nindent 4 }}
    {{- with .Values.envoyProxy.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
  {{- with .Values.envoyProxy.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.envoyProxy.serviceMonitor.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: nmp-envoy
      {{- include "nemo-platform.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    # Envoy admin /stats/prometheus endpoint for Prometheus metrics
    - port: admin
      path: /stats/prometheus
      {{- with .Values.envoyProxy.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.envoyProxy.serviceMonitor.scheme }}
      scheme: {{ . }}
      {{- end }}
{{- end }}
{{- end }}
