# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Dict, Iterable
from typing_extensions import TypedDict

__all__ = ["FlexibleEntryResponseParam"]


class FlexibleEntryResponseParam(TypedDict, total=False, extra_items=object):  # type: ignore[call-arg]
    """Flexible entry response that accepts any object shape.

    This flexibility enables the Intake service to store responses from various LLM providers
    and future model types without requiring schema updates.

    Required: either `choices` (successful response) or `error` (failed call).
    Common optional fields: `id`, `created`, `model`, `usage`, `system_fingerprint`, etc.
    """

    choices: Iterable[Dict[str, object]]
    """A list of response choices generated by the model.

    Each choice typically contains a message object with role, content, and optional
    tool_calls. The structure varies by provider but commonly includes fields like
    `index`, `message`, and `finish_reason`.
    """

    error: Dict[str, object]
    """
    Error envelope returned by the provider when the call failed (e.g., OpenAI's
    `{message, type, code, param}` shape). Mutually exclusive with `choices`: a
    response carries one or the other.
    """
