# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Dict, List, Optional
from datetime import datetime

from .adapter import Adapter
from ..._compat import PYDANTIC_V1, ConfigDict
from ..._models import BaseModel
from ..shared.model_spec import ModelSpec
from ..shared.prompt_data import PromptData
from ..shared.backend_format import BackendFormat
from ..shared.finetuning_type import FinetuningType
from ..shared.api_endpoint_data import APIEndpointData

__all__ = ["ModelEntity"]


class ModelEntity(BaseModel):
    """
    Model Entity represents a versioned model registered within the platform.
    Uses EntityBase for entity store compatibility.
    """

    id: str
    """Autogenerated id"""

    created_at: datetime
    """The timestamp of model entity creation"""

    name: str
    """Name of the entity.

    Name/workspace combo must be unique across all entities. Allowed characters:
    letters (a-z, A-Z), digits (0-9), underscores, hyphens, and dots.
    """

    updated_at: datetime
    """The timestamp of the last model entity update"""

    workspace: str
    """The workspace of the entity.

    Allowed characters: letters (a-z, A-Z), digits (0-9), underscores, hyphens, and
    dots.
    """

    adapters: Optional[List[Adapter]] = None
    """Adapters that have been created against this model"""

    api_endpoint: Optional[APIEndpointData] = None
    """Data about an inference endpoint."""

    backend_format: Optional[BackendFormat] = None
    """Inference backend API wire formats understood by IGW and middleware plugins."""

    base_model: Optional[str] = None
    """Link to another model which is used as a base for the current model"""

    custom_fields: Optional[Dict[str, object]] = None
    """Custom fields for additional metadata"""

    description: Optional[str] = None
    """Optional description of the model."""

    fileset: Optional[str] = None
    """
    A set of checkpoint files, configs, and other auxiliary info associated with
    this model - expected format {workspace}/{fileset_name}
    """

    finetuning_type: Optional[FinetuningType] = None
    """Finetuning types."""

    model_providers: Optional[List[str]] = None
    """
    List of ModelProvider workspace/name resource names that provide inference for
    this Model Entity
    """

    ownership: Optional[Dict[str, object]] = None
    """Ownership information for the model"""

    project: Optional[str] = None
    """The URN of the project associated with this model entity."""

    prompt: Optional[PromptData] = None
    """Configuration for prompt engineering."""

    spec: Optional[ModelSpec] = None
    """Detailed specification for a model."""

    trust_remote_code: Optional[bool] = None
    """Whether to trust remote code to load this model checkpoint."""

    if not PYDANTIC_V1:
        # allow fields with a `model_` prefix
        model_config = ConfigDict(protected_namespaces=tuple())
