# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""initial workspaces and entities tables

Revision ID: a870a05e48ca
Revises:
Create Date: 2026-02-13 14:48:31.344016

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a870a05e48ca"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspaces",
        sa.Column("id", sa.String(length=255), nullable=False, comment="System-generated UUID"),
        sa.Column("name", sa.String(length=255), nullable=False, comment="User-provided workspace name"),
        sa.Column("description", sa.Text(), nullable=True, comment="Optional description"),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("idx_workspaces_created", "workspaces", ["created_at"], unique=False)
    op.create_table(
        "entities",
        sa.Column("id", sa.String(length=255), nullable=False, comment="Compound identifier (entity_type-base58uuid)"),
        sa.Column("workspace", sa.String(length=255), nullable=False, comment="Workspace name"),
        sa.Column(
            "entity_type", sa.String(length=255), nullable=False, comment="Entity type (e.g., 'customization_config')"
        ),
        sa.Column("name", sa.String(length=255), nullable=False, comment="Entity name"),
        sa.Column("parent", sa.String(length=255), nullable=True, comment="Parent entity ID for nested entities"),
        sa.Column(
            "project",
            sa.String(length=255),
            nullable=True,
            comment="The name of the project associated with this entity",
        ),
        sa.Column("data", sa.JSON(), nullable=False, comment="Entity-specific data (JSON)"),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column(
            "db_version",
            sa.Integer(),
            server_default="1",
            nullable=False,
            comment="Database version of the entity for optimistic locking.",
        ),
        sa.ForeignKeyConstraint(["parent"], ["entities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace"], ["workspaces.name"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_entities_created", "entities", ["created_at"], unique=False)
    op.create_index("idx_entities_lookup", "entities", ["workspace", "entity_type", "name"], unique=False)
    op.create_index("idx_entities_parent", "entities", ["parent"], unique=False)
    op.create_index("idx_entities_project", "entities", ["project"], unique=False)
    op.create_index("idx_entities_type", "entities", ["workspace", "entity_type"], unique=False)
    op.create_index("idx_entities_updated", "entities", ["updated_at"], unique=False)
    op.create_index("idx_entities_workspace", "entities", ["workspace"], unique=False)
    op.create_index(
        "uq_entities_child",
        "entities",
        ["workspace", "entity_type", "parent", "name"],
        unique=True,
        sqlite_where=sa.text("parent IS NOT NULL"),
        postgresql_where=sa.text("parent IS NOT NULL"),
    )
    op.create_index(
        "uq_entities_root",
        "entities",
        ["workspace", "entity_type", "name"],
        unique=True,
        sqlite_where=sa.text("parent IS NULL"),
        postgresql_where=sa.text("parent IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """No-op for initial migration; there is no earlier revision to downgrade to."""
