# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""NeMo Platform common configuration module."""

from nmp.common.config.base import (
    NMP_CONFIG_FILE_PATH_DEFAULT,
    NMP_CONFIG_FILE_PATH_ENV_VAR,
    NMP_CONFIG_WARNINGS_DISABLED_ENV_VAR,
    NMP_CONTROLLERS_ENV_VAR,
    NMP_PREFIX_BASE,
    NMP_SERVICES_ENV_VAR,
    NMP_SIDECARS_ENV_VAR,
    AuthConfig,
    CommonServiceConfig,
    Configuration,
    DatabaseConfig,
    DockerConfig,
    EnvironmentFirstSettings,
    ImagePullSecret,
    PlatformConfig,
    Runtime,
    ServiceConfig,
    create_service_config_class,
    get_auth_config,
    get_common_service_config,
    get_platform_config,
    get_service_config,
    get_service_config_prefix,
    internal_field,
)
from nmp.common.config.paths import (
    NMP_DATA_DIR_ENV_VAR,
    XDG_DATA_HOME_ENV_VAR,
    nmp_user_data_dir,
)

__all__ = [
    "AuthConfig",
    "CommonServiceConfig",
    "Configuration",
    "Runtime",
    "DatabaseConfig",
    "DockerConfig",
    "EnvironmentFirstSettings",
    "ImagePullSecret",
    "NMP_CONFIG_FILE_PATH_DEFAULT",
    "NMP_CONFIG_FILE_PATH_ENV_VAR",
    "NMP_CONFIG_WARNINGS_DISABLED_ENV_VAR",
    "NMP_DATA_DIR_ENV_VAR",
    "NMP_PREFIX_BASE",
    "NMP_SERVICES_ENV_VAR",
    "NMP_CONTROLLERS_ENV_VAR",
    "NMP_SIDECARS_ENV_VAR",
    "PlatformConfig",
    "ServiceConfig",
    "XDG_DATA_HOME_ENV_VAR",
    "create_service_config_class",
    "get_auth_config",
    "get_common_service_config",
    "get_platform_config",
    "get_service_config",
    "get_service_config_prefix",
    "internal_field",
    "nmp_user_data_dir",
]
