# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Value objects for the Intake service."""

from datetime import datetime, timezone
from typing import Annotated, Any, Dict, List, Literal, Optional, Self, TypeAlias, Union

from nmp.common.entities.values import Value
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from .enums import MessageRole, ThumbDirection

# ---------------------------------------------------------------------------
# Type aliases
# ---------------------------------------------------------------------------

# Constrained string type alias for ≤256-char values (schema adds maxLength)
ShortStr: TypeAlias = Annotated[str, Field(max_length=256)]

# Allowed value types for user-action metadata entries
UserActionValue = Union[ShortStr, List[ShortStr], bool, int, float]


# ---------------------------------------------------------------------------
# Flexible Messages and Requests
# ---------------------------------------------------------------------------


class FlexibleMessage(BaseModel):
    """A flexible message model that requires a valid role field but allows any other fields.

    This flexibility enables the Intake service to store messages from various LLM providers
    and future model types without requiring schema updates. Additional fields like `content`,
    `name`, `tool_calls`, `tool_call_id`, etc. are all accepted.

    Examples of additional fields:
    - `content`: The message text or content
    - `name`: Name of the user or function
    - `tool_calls`: Tool/function calls in the message
    - `tool_call_id`: ID of the tool call being responded to
    """

    model_config = ConfigDict(extra="allow")

    role: MessageRole = Field(
        ...,
        description=(
            "The role of the message sender. Must be one of: user, system, assistant, developer, tool, or function."
        ),
    )


class FlexibleEntryRequest(BaseModel):
    """Flexible entry request that accepts any object shape.

    This flexibility enables the Intake service to store requests from various LLM providers
    (OpenAI, Anthropic, NIM, etc.) and future model types (embeddings, multimodal, etc.)
    without requiring schema updates.

    Required fields: `messages` and `model`
    Common optional fields: `temperature`, `max_tokens`, `top_p`, `tools`, `tool_choice`,
    `stream`, `response_format`, etc.
    """

    model_config = ConfigDict(extra="allow")

    messages: List[FlexibleMessage] = Field(
        ...,
        description=(
            "A list of messages comprising the conversation. Each message must have a valid role. "
            "Additional fields like `content`, `tool_calls`, etc. are provider-specific."
        ),
    )
    model: str = Field(
        ...,
        description="The model identifier used for this request (e.g., 'gpt-4', 'llama-3-70b', 'claude-3-opus').",
    )


class FlexibleEntryResponse(BaseModel):
    """Flexible entry response that accepts any object shape.

    This flexibility enables the Intake service to store responses from various LLM providers
    and future model types without requiring schema updates.

    Required: either `choices` (successful response) or `error` (failed call).
    Common optional fields: `id`, `created`, `model`, `usage`, `system_fingerprint`, etc.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={
            "oneOf": [
                {"required": ["choices"]},
                {"required": ["error"]},
            ],
        },
    )

    choices: Optional[List[Dict[str, Any]]] = Field(
        default=None,
        description=(
            "A list of response choices generated by the model. Each choice typically contains "
            "a message object with role, content, and optional tool_calls. "
            "The structure varies by provider but commonly includes fields like `index`, `message`, and `finish_reason`."
        ),
    )
    error: Optional[Dict[str, Any]] = Field(
        default=None,
        description=(
            "Error envelope returned by the provider when the call failed (e.g., OpenAI's "
            "`{message, type, code, param}` shape). Mutually exclusive with `choices`: a response "
            "carries one or the other."
        ),
    )

    @model_validator(mode="after")
    def _require_choices_or_error(self) -> Self:
        # XOR by presence: choices=[] still counts as "present" — the entries endpoint
        # historically accepts callers that supply an empty list, so we treat omission
        # (None) as the only "missing" state.
        if (self.choices is None) == (self.error is None):
            if self.choices is None:
                raise ValueError("response must include either `choices` or `error`")
            raise ValueError("response cannot include both `choices` and `error`")
        return self


# ---------------------------------------------------------------------------
# Core Value Objects
# ---------------------------------------------------------------------------


class Usage(Value):
    """Structured usage metrics captured at log time.

    Every field is optional so producers can populate whatever they have without
    schema breakage. Stored as the entry-level ``usage`` field so filters can
    reach it via ``data.usage.<field>`` entity-store paths.
    """

    model: Optional[str] = Field(
        default=None,
        description="The actual model that served the request (after any routing). May differ from the model in the request body.",
    )
    started_at: Optional[datetime] = Field(
        default=None,
        description="UTC timestamp when the upstream LLM call started.",
        json_schema_extra={"format": "date-time"},
    )
    ended_at: Optional[datetime] = Field(
        default=None,
        description="UTC timestamp when the upstream LLM call ended.",
        json_schema_extra={"format": "date-time"},
    )
    latency_ms: Optional[int] = Field(
        default=None,
        ge=0,
        description="Wall-clock latency of the upstream LLM call, in milliseconds.",
        json_schema_extra={"minimum": 0},
    )
    cost_usd: Optional[float] = Field(
        default=None,
        ge=0,
        description="Total estimated cost of this call, in USD.",
        json_schema_extra={"minimum": 0},
    )
    cost_input_usd: Optional[float] = Field(
        default=None,
        ge=0,
        description="Estimated cost attributed to input tokens, in USD.",
        json_schema_extra={"minimum": 0},
    )
    cost_output_usd: Optional[float] = Field(
        default=None,
        ge=0,
        description="Estimated cost attributed to output tokens, in USD.",
        json_schema_extra={"minimum": 0},
    )
    input_tokens: Optional[int] = Field(
        default=None,
        ge=0,
        description="Number of input tokens consumed.",
        json_schema_extra={"minimum": 0},
    )
    output_tokens: Optional[int] = Field(
        default=None,
        ge=0,
        description="Number of output tokens produced.",
        json_schema_extra={"minimum": 0},
    )
    cached_tokens: Optional[int] = Field(
        default=None,
        ge=0,
        description="Number of input tokens served from a prompt cache (subset of input_tokens).",
        json_schema_extra={"minimum": 0},
    )

    @field_validator("started_at", "ended_at")
    @classmethod
    def _ensure_utc_timestamp(cls, value: Optional[datetime]) -> Optional[datetime]:
        if value is None:
            return value
        if value.tzinfo is None or value.utcoffset() is None:
            return value.replace(tzinfo=timezone.utc)
        return value.astimezone(timezone.utc)

    @model_validator(mode="after")
    def _validate_timestamp_order(self) -> Self:
        if self.started_at is not None and self.ended_at is not None and self.ended_at < self.started_at:
            raise ValueError("ended_at must be greater than or equal to started_at")
        return self

    @model_validator(mode="after")
    def _validate_cached_tokens(self) -> Self:
        if self.cached_tokens is not None and self.input_tokens is not None and self.cached_tokens > self.input_tokens:
            raise ValueError("cached_tokens must be less than or equal to input_tokens")
        return self


class EntryData(Value):
    """Entry data containing the request and response for an LLM interaction."""

    request: FlexibleEntryRequest = Field(..., description="Raw request payload recorded from the client.")
    response: FlexibleEntryResponse = Field(..., description="Raw response payload generated by the model.")


class EntryContext(Value):
    """Contextual metadata attached to every entry record.

    Keeping these grouped in a dedicated object avoids polluting the top-level
    entity schema and makes it trivial to extend without breaking compatibility.
    """

    # Required fields ------------------------------------------------------

    app: str = Field(
        ...,
        description=(
            "Reference to the app that produced this entry, in the form `workspace/name`. "
            "If the app doesn't exist, it will be automatically created when the entry is ingested."
        ),
    )
    task: Optional[str] = Field(
        ...,
        description=(
            "Name of the task within the app (e.g., 'chat', 'completion', 'tool-call'). "
            "If the task doesn't exist, it will be automatically created when the entry is ingested."
        ),
    )

    thread_id: Optional[str] = Field(
        default=None,
        description=(
            "Logical thread identifier that groups related entries in a multi-turn conversation. "
            "If provided, entries with the same thread_id are treated as part of the same conversation. "
            "If omitted, the entry is treated as a single-turn interaction (e.g., a standalone tool call or completion)."
        ),
    )

    user_id: Optional[str] = Field(
        default=None,
        description=(
            "Identifier of the application's end-user who triggered this LLM interaction. "
            "This represents the person using your application (e.g., 'customer_123', 'employee@company.com'), "
            "NOT the service account that created the entry record (see ownership.created_by for that). "
            "Use this to track which of your users a conversation belongs to, filter entries by user, "
            "and enable per-user analytics. Format is application-defined."
        ),
    )

    # Optional tracing fields -----------------------------------------------
    trace_id: Optional[str] = Field(
        default=None,
        description=(
            "Distributed trace identifier (e.g., W3C traceparent). Intake stores it "
            "verbatim and does not use it at ingestion time; helps with later cross-system joins."
        ),
    )

    session_id: Optional[str] = Field(
        default=None,
        description=(
            "Long-lived session identifier (e.g., user account or browser session). "
            "Stored for post-processing analytics; not used by the Intake service at runtime."
        ),
    )

    # Timestamps
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp when the entry was created.",
    )


class UserRating(Value):
    """User's rating/evaluation of an AI response.

    This captures various forms of end-user feedback about a model's response, including
    binary thumbs up/down ratings, numeric scores, free-text opinions, suggested rewrites,
    and structured category ratings.

    Either `thumb` or `rating` should be provided (they are mutually exclusive), but all
    fields are optional to accommodate different feedback collection patterns.
    """

    thumb: Optional[ThumbDirection] = Field(
        default=None,
        description=(
            'Binary feedback: "up" for 👍 or "down" for 👎. '
            "Mutually exclusive with `rating`. Use this for simple thumbs up/down UI elements."
        ),
    )
    rating: Optional[float] = Field(
        default=None,
        ge=0,
        description=(
            "Numeric rating (e.g., 1-5 stars) provided by the end user. "
            "Mutually exclusive with `thumb`. Use this for star ratings or numeric scales."
        ),
    )
    opinion: Optional[str] = Field(
        default=None,
        min_length=1,
        max_length=2_000,
        description="Free-text comment from the end user describing their opinion of the response.",
    )
    rewrite: Optional[str] = Field(
        default=None,
        min_length=1,
        max_length=10_000,
        description=(
            "End-user's suggested text replacement for the generated response. "
            "This is the user's idea of what the response should have been."
        ),
    )
    chosen_index: Optional[int] = Field(
        default=None,
        ge=0,
        description=(
            "Zero-based index of the response option the user selected when multiple responses were returned. "
            "Use this when showing users multiple completion choices and tracking which one they picked."
        ),
    )
    categories: Optional[Dict[str, Union[float, str]]] = Field(
        default=None,
        description=(
            "Application-specific category ratings as key-value pairs. "
            "Use this for custom rating dimensions (e.g., {'helpfulness': 4, 'accuracy': 5, 'tone': 'professional'}). "
            "Useful for radio buttons, dropdowns, or multi-dimensional rating systems."
        ),
    )

    @field_validator("rewrite")
    @classmethod
    def _strip_whitespace(cls, v: Optional[str]):  # noqa: D401, N805
        return v.strip() if isinstance(v, str) else v


# ---------------------------------------------------------------------------
# Events Base Class
# ---------------------------------------------------------------------------


class _BaseEvent(Value):  # noqa: D101 (internal base)
    """Base class for all entry events."""

    id: Optional[str] = Field(
        default=None,
        description="Unique identifier for the event. Populated when retrieved from database.",
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp when the record was created.",
    )
    created_by: Optional[Dict[str, str]] = Field(
        default=None,
        description="Identifier of the user or system that generated the record. Can be set of key-value pairs.",
    )


# ---------------------------------------------------------------------------
# Event Types
# ---------------------------------------------------------------------------


class UserFeedbackEvent(_BaseEvent):
    """Structured feedback supplied by an end-user.

    This event captures various forms of end-user feedback about a model's response,
    including binary thumbs up/down ratings, numeric scores, free-text opinions,
    suggested rewrites, and structured category ratings.

    Either `thumb` or `rating` should be provided (they are mutually exclusive), but all
    feedback fields are optional to accommodate different feedback collection patterns.
    """

    model_config = ConfigDict(extra="forbid")

    event_type: Literal["user_feedback"] = "user_feedback"  # noqa: A003

    # Feedback specifics ----------------------------------------------------
    thumb: Optional[ThumbDirection] = Field(
        default=None,
        description=(
            'Binary feedback: "up" for 👍 or "down" for 👎. '
            "Mutually exclusive with `rating`. Use this for simple thumbs up/down UI elements."
        ),
    )
    rating: Optional[float] = Field(
        default=None,
        ge=0,
        description=(
            "Numeric rating (e.g., 1-5 stars) provided by the end user. "
            "Mutually exclusive with `thumb`. Use this for star ratings or numeric scales."
        ),
    )
    opinion: Optional[str] = Field(
        default=None,
        min_length=1,
        max_length=2_000,
        description="Free-text comment from the end user describing their opinion of the response.",
    )
    rewrite: Optional[str] = Field(
        default=None,
        min_length=1,
        max_length=10_000,
        description=(
            "End-user's suggested text replacement for the generated response. "
            "This is the user's idea of what the response should have been."
        ),
    )
    chosen_index: Optional[int] = Field(
        default=None,
        ge=0,
        description=(
            "Zero-based index of the response option the user selected when multiple responses were returned. "
            "Use this when showing users multiple completion choices and tracking which one they picked."
        ),
    )
    categories: Optional[Dict[str, Union[float, str]]] = Field(
        default=None,
        description=(
            "Application-specific category ratings as key-value pairs. "
            "Use this for custom rating dimensions (e.g., {'helpfulness': 4, 'accuracy': 5, 'tone': 'professional'}). "
            "Useful for radio buttons, dropdowns, or multi-dimensional rating systems."
        ),
    )

    @field_validator("rewrite")
    @classmethod
    def _strip_whitespace(cls, v: Optional[str]):  # noqa: D401, N805
        return v.strip() if isinstance(v, str) else v


class UserActionEvent(_BaseEvent):
    """Free-form user action captured by the client application.

    Use this to track arbitrary user interactions with AI responses, such as copying code,
    clicking share buttons, making purchases, or any other measurable action.

    The action identifier must be ≤256 characters and should use snake-case or kebab-case
    for consistency (e.g., ``share_clicked``, ``code_copied``, ``purchase_made``).
    """

    model_config = ConfigDict(extra="forbid")

    event_type: Literal["user_action"] = "user_action"  # noqa: A003

    action: str = Field(
        ...,
        max_length=256,
        description=(
            "Descriptive name for the action taken by the user (e.g., 'share_clicked', 'code_copied', 'link_followed'). "
            "Use snake-case or kebab-case. This is a label, not a unique identifier—multiple events can have the same action name."
        ),
    )
    metadata: Dict[ShortStr, UserActionValue] = Field(
        default_factory=dict,
        description=(
            "Optional key-value pairs with additional context about the action (max 16 entries). "
            "Use this for details like user IDs, item IDs, timestamps, A/B test variants, or any other "
            "information useful for downstream training or evaluation pipelines. "
            "Example: {'user_id': '12345', 'experiment': 'variant_b', 'item_purchased': 'product_456'}."
        ),
        max_length=16,
    )


class ReviewerAnnotationEvent(UserFeedbackEvent):
    """Structured annotation supplied by a reviewer or expert evaluator.

    A reviewer annotation is similar to user feedback but includes an additional capability
    to provide a complete replacement response. This is useful when human experts need to
    correct not just the text but also structured elements like tool calls, function outputs,
    or other response metadata.

    Inherits all feedback fields from UserFeedbackEvent (thumb, rating, opinion, rewrite,
    chosen_index, categories) and adds response_override for full response replacement.
    """

    event_type: Literal["reviewer_annotation"] = "reviewer_annotation"  # type: ignore[assignment]

    response_override: Optional[Dict[str, Any]] = Field(
        default=None,
        description=(
            "Complete JSON object that replaces the original model response when exporting data. "
            "Unlike the `rewrite` field (which is just text), this can include tool calls, function outputs, "
            "and all other response metadata. When an entry with response_override is exported, you can choose "
            "to use this corrected response instead of the original. "
            "Example: {'choices': [{'message': {'role': 'assistant', 'content': 'Corrected text', "
            "'tool_calls': [...]}}]}"
        ),
    )


class EvaluatorResultEvent(_BaseEvent):
    """Result produced by an automated evaluator.

    Use this for any non-human scorer that emits a judgement about an entry:
    eval-framework verifier rewards, LLM-judge ratings, auditor probe results, etc.
    Distinct from UserFeedbackEvent (human end-user feedback) and ReviewerAnnotationEvent
    (human expert annotation).
    """

    model_config = ConfigDict(extra="forbid")

    event_type: Literal["evaluator_result"] = "evaluator_result"  # noqa: A003

    name: str = Field(
        ...,
        max_length=256,
        description=(
            "Identifier of the evaluator that produced this result "
            "(e.g., 'harbor.verifier', 'evaluator.llm_judge', 'auditor.pii_probe')."
        ),
    )
    score: Optional[Union[int, float, str]] = Field(
        default=None,
        description=(
            "The result value: a number (e.g., reward, rating, probability) or a string "
            "(e.g., 'pass', 'fail', a category label). Semantics are defined by the evaluator."
        ),
    )
    metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        description=(
            "Free-form additional context about this result "
            "(e.g., supporting metrics, trial_name, rubric_version, evaluator config snapshot)."
        ),
    )


# Discriminated union --------------------------------------------------------

EntryEvent = Annotated[
    Union[UserFeedbackEvent, UserActionEvent, ReviewerAnnotationEvent, EvaluatorResultEvent],
    Field(discriminator="event_type"),
]


# ---------------------------------------------------------------------------
# Export Job Configuration and Status
# ---------------------------------------------------------------------------


class ExportConfig(Value):
    """Configuration for an export job.

    Defines what entries to export and how to format them.
    """

    filters: Optional[Dict[str, Any]] = Field(
        default=None,
        description=(
            "Filter criteria for selecting entries (workspace, app, task, thread_id, external_id, "
            "has_thumb, has_rating, longest_per_thread, model, etc.)"
        ),
    )

    search: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Search criteria for finding entries",
    )

    limit: Optional[int] = Field(
        default=1000,
        description="Maximum number of entries to export. None means no limit.",
    )

    format_options: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Format options for the export (e.g., row_transformation)",
    )


class ExportStatusDetails(Value):
    """Detailed status information for an export job."""

    entries_count: int = Field(
        default=0,
        description="Number of entries exported",
    )

    progress: Optional[float] = Field(
        default=None,
        description="Progress percentage (0-100)",
    )

    error_message: Optional[str] = Field(
        default=None,
        description="Error message if the job failed",
    )
