# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""
License report generator using osv-scanner.

This module handles the generation of license reports by:
1. Running osv-scanner on lockfiles
2. Formatting the JSON output into human-readable tables
3. Running scans in parallel for multiple projects
"""

import json
import logging
import shutil
import subprocess
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Optional

from nemo_platform_sdk_tools.license.format_osv_licenses import format_licenses_table
from nemo_platform_sdk_tools.license.formats import get_formatter
from nemo_platform_sdk_tools.license.license_utils import ALLOWED_LICENSES, get_local_packages, resolve_license

logger = logging.getLogger(__name__)

OVERRIDES_FILE = overrides_file = Path(__file__).parent / "overrides.yaml"


class LicenseGenerationError(Exception):
    """Raised when license generation fails."""

    pass


def get_osv_scanner() -> Path:
    """
    Check if osv-scanner is available.

    Returns:
        Path to osv-scanner executable

    Raises:
        LicenseGenerationError: If osv-scanner is not found
    """
    osv_path = shutil.which("osv-scanner")
    if not osv_path:
        raise LicenseGenerationError("osv-scanner not found. Please install it first.")
    return Path(osv_path)


def _sanitize_osv_json(output_file: Path) -> None:
    """
    Remove machine-specific paths from OSV JSON output.

    The osv-scanner includes absolute paths like /Users/username/code/nmp/uv.lock
    which cause unnecessary diffs when different developers run the tool.
    """

    with open(output_file, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Remove path from source objects in results
    for result in data.get("results", []):
        source = result.get("source", {})
        if "path" in source:
            del source["path"]

    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)


def _sanitize_requirements_file(requirements_file: Path) -> None:
    """
    Remove machine-specific absolute paths from requirements file comments.

    The uv export command includes a comment with the full command including
    absolute paths like /Users/username/dev/nmp/third_party/requirements.txt
    which cause unnecessary diffs when different developers run the tool.
    """
    with open(requirements_file, "r", encoding="utf-8") as f:
        lines = f.readlines()

    # Replace absolute paths with relative paths in the header comment
    if lines and lines[0].startswith("# This file was autogenerated by uv"):
        # Just keep the generic comment without the specific command
        lines[0] = "# This file was autogenerated by uv via the following command:\n"
        if len(lines) > 1 and lines[1].startswith("#    uv export"):
            # Make the path relative by extracting just the filename
            output_file_name = requirements_file.name
            lines[1] = f"#    uv export --no-dev --output-file third_party/{output_file_name}\n"

    with open(requirements_file, "w", encoding="utf-8") as f:
        f.writelines(lines)


def run_osv_scanner(lockfile: Path, output_file: Path, cwd: Optional[Path] = None) -> None:
    """
    Run osv-scanner on a lockfile and save JSON output.

    Args:
        lockfile: Path to uv.lock or other lockfile
        output_file: Where to save the JSON output
        cwd: Working directory to run the command in

    Raises:
        LicenseGenerationError: If osv-scanner fails
    """
    get_osv_scanner()

    cmd = [
        "osv-scanner",
        "scan",
        "source",
        "--licenses",
        "--lockfile",
        str(lockfile),
        "--format",
        "json",
        "--all-packages",
        "--output",
        str(output_file),
    ]

    logger.debug(f"Running: {' '.join(cmd)}")
    logger.debug(f"Working directory: {cwd or Path.cwd()}")

    try:
        # Run osv-scanner, suppress stderr output (vulnerability warnings)
        result = subprocess.run(
            cmd,
            cwd=cwd,
            text=True,
            check=False,  # osv-scanner returns non-zero when vulnerabilities found
        )

        # osv-scanner returns non-zero exit codes for various reasons
        # We only care if the output file was created
        if not output_file.exists():
            raise LicenseGenerationError(
                f"osv-scanner failed to create output file: {output_file}\n"
                f"Exit code: {result.returncode}\n"
                f"Stdout: {result.stdout}\n"
                f"Stderr: {result.stderr}"
            )

        # Remove machine-specific paths from output
        _sanitize_osv_json(output_file)

        logger.info(f"✓ Generated OSV JSON: {output_file}")

    except FileNotFoundError:
        raise LicenseGenerationError("osv-scanner command not found")


def format_licenses(
    osv_json: Path, output_file: Path, overrides_file: Optional[Path] = None, format_type: str = "table"
) -> None:
    """
    Format OSV JSON output into the desired format.

    Args:
        osv_json: Path to OSV scanner JSON output
        output_file: Where to save the formatted output
        overrides_file: Optional path to license overrides YAML
        format_type: Output format (table, jsonl, json, csv, markdown, text)

    Raises:
        LicenseGenerationError: If formatting fails
    """

    try:
        logger.debug(f"Formatting {osv_json} -> {output_file} (format: {format_type})")

        # Load the JSON
        with open(osv_json) as f:
            import json

            data = json.load(f)

        # Get overrides
        overrides = {}
        if overrides_file and overrides_file.exists():
            import yaml

            with open(overrides_file) as f:
                override_data = yaml.safe_load(f)
                overrides = override_data.get("overrides", {})

        # Get local packages to exclude
        workspace_root = osv_json.parent.parent  # Assuming osv_json is in third_party/
        local_packages = get_local_packages(workspace_root)

        # Use old formatter for backward compatibility
        if format_type == "table":
            formatted = format_licenses_table(data, overrides, local_packages)
        else:
            # Use new formatter
            formatter = get_formatter(format_type)

            # Extract package info from OSV data
            packages = []
            if "results" in data and len(data["results"]) > 0:
                for pkg_data in data["results"][0].get("packages", []):
                    pkg = pkg_data.get("package", {})
                    name = pkg.get("name", "")
                    version = pkg.get("version", "")
                    licenses = pkg_data.get("licenses", [])

                    # Skip local packages
                    from nemo_platform_sdk_tools.license.license_utils import (
                        get_override_key_for_package,
                        normalize_package_name,
                    )

                    if normalize_package_name(name) in local_packages:
                        continue

                    # Check overrides (use base name so +cu129 variants match)
                    override_key = get_override_key_for_package(name, version)
                    if override_key in overrides:
                        license_str = overrides[override_key]
                    elif not licenses:
                        continue
                    else:
                        # Resolve to a single license, preferring allowed ones
                        license_str = resolve_license(licenses, ALLOWED_LICENSES)

                    packages.append({"name": name, "version": version, "license": license_str.upper()})

            # Deduplicate by name (keep first occurrence)
            seen_names = set()
            unique_packages = []
            for pkg in packages:
                if pkg["name"] not in seen_names:
                    seen_names.add(pkg["name"])
                    unique_packages.append(pkg)

            # Sort by name
            unique_packages.sort(key=lambda x: x["name"].lower())

            # Format using selected formatter
            formatted = formatter.format(unique_packages)

        # Write output
        with open(output_file, "w") as f:
            f.write(formatted)

        logger.debug(f"✓ Generated license {format_type}: {output_file}")

    except Exception as e:
        raise LicenseGenerationError(f"Failed to format licenses: {e}")


def generate_lockfile_without_dev_dependencies(
    lockfile_dir: Path,
    output_lockfile: Path,
    extras: Optional[list[str]] = None,
    packages: Optional[list[str]] = None,
) -> Path:
    """
    Generate a lockfile without dev dependencies.

    Args:
        lockfile_dir: Path to the directory containing the lockfile
        output_lockfile: Path to the output lockfile
        extras: Optional list of extras to include (e.g., ["cu129"])
        packages: Optional list of workspace packages to include via --package flag.
            Required when extras reference workspace member dependencies, since
            uv export does not propagate workspace packages' extras' transitive
            dependencies without explicitly specifying --package.

    Returns:
        Path to the output lockfile
    """

    cmd = [
        "uv",
        "export",
        "--no-dev",
    ]

    # Add packages if specified (needed to resolve workspace member extras)
    if packages:
        for package in packages:
            cmd.extend(["--package", package])

    # Add extras if specified
    if extras:
        for extra in extras:
            cmd.extend(["--extra", extra])

    cmd.extend(
        [
            "--quiet",
            "--output-file",
            str(output_lockfile),
        ]
    )

    logger.debug(f"Running: {' '.join(cmd)}")
    logger.debug(f"Working directory: {lockfile_dir}")

    try:
        subprocess.run(
            cmd,
            cwd=lockfile_dir,
            text=True,
            check=True,
        )
        # Sanitize the generated requirements file to remove machine-specific paths
        _sanitize_requirements_file(output_lockfile)
    except Exception as e:
        raise LicenseGenerationError(f"Failed to generate lockfile without dev dependencies: {e}")
    return output_lockfile


def generate_project_licenses(
    project_name: str,
    lockfile_dir: Path,
    output_lockfile: Path,
    osv_json: Path,
    output_file: Path,
    overrides_file: Optional[Path] = None,
    cwd: Optional[Path] = None,
    format_type: str = "table",
    extras: Optional[list[str]] = None,
    packages: Optional[list[str]] = None,
) -> str:
    """
    Generate licenses for a single project.

    Args:
        project_name: Name of the project (for logging)
        lockfile_dir: Path to the directory containing the lockfile
        output_lockfile: Path to the output lockfile
        osv_json: Where to save OSV JSON output
        output_file: Where to save the formatted license table
        overrides_file: Optional path to license overrides
        cwd: Working directory for osv-scanner
        format_type: Output format (table, jsonl, json, csv, markdown, text)
        extras: Optional list of extras to include (e.g., ["cu129"])
        packages: Optional list of workspace packages to include via --package flag

    Returns:
        Success message

    Raises:
        LicenseGenerationError: If generation fails
    """
    try:
        logger.info(f"Generating licenses for {project_name}...")

        generate_lockfile_without_dev_dependencies(lockfile_dir, output_lockfile, extras=extras, packages=packages)

        # Run osv-scanner
        run_osv_scanner(output_lockfile, osv_json, cwd=cwd)

        # Format output
        format_licenses(osv_json, output_file, overrides_file, format_type=format_type)

        return f"✓ Generated {output_file}"

    except Exception as e:
        logger.error(f"Failed to generate licenses for {project_name}: {e}")
        raise


def get_projects(workspace_root: Path) -> list[dict]:
    import os

    # Check for environment variable overrides (used in CI)
    license_dir_str = os.environ.get("LICENSE_DIR", str(workspace_root / "third_party"))
    license_dir = Path(license_dir_str)

    main_license_name = os.environ.get("LICENSE_NAME", "licenses.jsonl")

    # Define projects to scan
    projects = [
        {
            "name": "main",
            "lockfile_dir": workspace_root,
            "osv_json": license_dir / "osv-licenses.json",
            "output_lockfile": license_dir / "requirements-main.txt",
            "output_file": license_dir / main_license_name,
            "cwd": workspace_root,
            "overrides_file": OVERRIDES_FILE,
            "packages": ["nemoplatform"],
        },
    ]
    return projects


def generate_all_licenses(workspace_root: Path, parallel: bool = True, format_type: str = "table") -> None:
    """
    Generate license reports for the main project.

    Args:
        workspace_root: Path to the workspace root
        parallel: Whether to run scans in parallel (default: True)
        format_type: Output format (table, jsonl, json, csv, markdown, text)

    Raises:
        LicenseGenerationError: If generation fails
    """
    projects = get_projects(workspace_root)
    if parallel:
        logger.info("Generating licenses for main project...")

        with ThreadPoolExecutor(max_workers=2) as executor:
            futures = {
                executor.submit(
                    generate_project_licenses,
                    proj["name"],
                    proj["lockfile_dir"],
                    proj["output_lockfile"],
                    proj["osv_json"],
                    proj["output_file"],
                    proj["overrides_file"],
                    proj.get("cwd"),
                    format_type,
                    proj.get("extras"),
                    proj.get("packages"),
                ): proj["name"]
                for proj in projects
            }

            for future in as_completed(futures):
                project_name = futures[future]
                try:
                    message = future.result()
                    logger.info(message)
                except Exception as e:
                    logger.error(f"Error generating licenses for {project_name}: {e}")
                    raise
    else:
        # Sequential execution
        for proj in projects:
            message = generate_project_licenses(
                proj["name"],
                proj["lockfile_dir"],
                proj["output_lockfile"],
                proj["osv_json"],
                proj["output_file"],
                proj["overrides_file"],
                proj.get("cwd"),
                format_type,
                proj.get("extras"),
                proj.get("packages"),
            )
            logger.info(message)

    logger.info("\nLicense generation complete!")
