# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# run via root directory:
# uv run python docs/_scripts/run_notebooks.py docs/
#
# Options:
#   --language python  Run only Python cells (default, skip shell/curl)
#   --language shell   Run only shell cells (skip Python)
#   --use-temporary-venv  Create and use a temporary virtualenv for running notebooks
#   --requirements FILE  Install packages from requirements file using uv (requires --use-temporary-venv)
#
# This script finds and runs notebooks with the @nemo-nb: process marker.
# It supports both:
#   - .ipynb files (standard Jupyter notebooks)
#   - .md files (markdown notebooks using nemo-nb format)
#
# For .md files, the script converts them to .ipynb first, runs them,
# then cleans up the generated notebook.
#
# Core logic lives in nmp.testing.notebooks and can be imported directly.

import argparse
import sys

from dotenv import load_dotenv
from nmp.testing.notebooks import run_notebooks

# Load environment variables from .env file if it exists
load_dotenv()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run notebooks in a directory.")
    parser.add_argument("dir", help="Directory containing notebooks to run")
    parser.add_argument(
        "--language",
        choices=["all", "python", "shell"],
        default="python",
        help="Which cells to execute: python only (default), all of them, or shell only",
    )
    parser.add_argument(
        "--keep-temp-files",
        action="store_true",
        help="Keep the temporary files generated by the notebooks",
    )
    parser.add_argument(
        "--use-temporary-venv",
        action="store_true",
        help="Create a temporary virtualenv for running notebooks. "
        "This allows testing library installations from scratch in a clean environment.",
    )
    parser.add_argument(
        "--requirements",
        type=str,
        default=None,
        metavar="FILE",
        help="Path to a requirements.txt file to install in the temporary virtualenv. "
        "Requires --use-temporary-venv. Packages are installed using 'uv pip install -r'.",
    )
    args = parser.parse_args()

    sys.exit(
        run_notebooks(
            args.dir, args.language, args.keep_temp_files, args.use_temporary_venv, args.requirements
        )
    )
