// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { defineConfig, OutputClient, type ConfigExternal } from 'orval';
import {
  DEFAULT_CLIENT,
  DEFAULT_INPUT,
  DEFAULT_SCHEMAS,
  DEFAULT_TARGET,
  serviceConfigs,
} from './orval/constants';
import { operationNameOverride } from './orval/operationNameOverride';

const input = process.env.ORVAL_INPUT ?? DEFAULT_INPUT;
const target = process.env.ORVAL_TARGET ?? DEFAULT_TARGET;
const schemas = process.env.ORVAL_SCHEMAS ?? DEFAULT_SCHEMAS;
const client = (process.env.ORVAL_CLIENT as OutputClient) ?? DEFAULT_CLIENT;
const isZodClient = client === 'zod';
const servicePath = serviceConfigs[process.env.ORVAL_SERVICE as keyof typeof serviceConfigs]?.path;

const configs = {
  nemoMicroservices: {
    input,
    output: {
      httpClient: 'axios',
      namingConvention: 'PascalCase',
      target,
      schemas,
      client,
      clean: true,
      mode: isZodClient ? 'tags' : 'single',
      urlEncodeParameters: true, // Use this property to enable URL encoding of path/query parameters.
      override: {
        header: (info: { title?: string }): string[] => [
          `SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.`,
          `SPDX-License-Identifier: Apache-2.0`,
          ``,
          `Generated by Orval 🍺`,
          `Do not edit manually.`,
          ...(info.title ? [info.title] : []),
        ],
        mutator: !isZodClient
          ? {
              path: `./generated/fetchers/${servicePath}.ts`,
              name: 'customFetch',
            }
          : undefined,
        operationName: operationNameOverride,
        fetch: {
          // This is necessary to make the react-query hooks have the proper type for `data`. Without this,
          // for example, `data` would be of type `ProjectsPage | HttpValidationError` instead of `ProjectsPage`.
          // We want `data` from `useQuery` to always be the happy path type, and everything else to be an error.
          includeHttpResponseReturnType: false,
        },
        query: {
          // Generates useSuspenseQuery hooks for every endpoint
          useSuspenseQuery: true,
        },
      },
    },
    hooks: {
      afterAllFilesWrite: `tsx ./orval/format-generated.ts ${servicePath}`,
    },
  },
};

export default defineConfig(configs as ConfigExternal);
