{{- if .Values.core.enabled }}
{{- if .Values.core.controller.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nmp-core.controllerServiceAccountName" . }}
  labels:
    app.kubernetes.io/component: nmp-core-controller
    {{- include "nemo-platform.labels" . | nindent 4 }}
  {{- with .Values.core.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.core.controller.serviceAccount.automount }}
{{- end }}
{{- end }}
