models:
  huggingface_model_puller: "nvcr.io/nvidia/nemo-microservices/nds-v2-huggingface-cli:25.10"
  controller:
    interval_seconds: 5   # Faster iteration for development
    model_deployment_garbage_collection_ttl_seconds: 30
    backends:
      docker:
        enabled: true

inference_gateway: {}
