# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""initial_migration

Revision ID: a7e3b1e7355b
Revises:
Create Date: 2025-10-14 11:01:23.029457

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7e3b1e7355b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "intake_apps",
        sa.Column("type_prefix", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("schema_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("namespace", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("project", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("custom_fields", sa.JSON(), nullable=True),
        sa.Column("ownership", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace", "name"),
    )
    op.create_table(
        "intake_entries",
        sa.Column("type_prefix", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column("user_rating", sa.JSON(), nullable=True),
        sa.Column("events", sa.JSON(), nullable=True),
        sa.Column("schema_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("namespace", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("project", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("custom_fields", sa.JSON(), nullable=True),
        sa.Column("ownership", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id", name="uq_entry_external_id"),
    )
    op.create_table(
        "intake_export_jobs",
        sa.Column("type_prefix", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("output_file_url", sa.String(), nullable=True),
        sa.Column("status_details", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "PENDING",
                "RUNNING",
                "CANCELLED",
                "CANCELLING",
                "FAILED",
                "COMPLETED",
                "READY",
                "UNKNOWN",
                name="jobstatus",
            ),
            nullable=False,
        ),
        sa.Column("schema_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("namespace", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("project", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("custom_fields", sa.JSON(), nullable=True),
        sa.Column("ownership", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "intake_tasks",
        sa.Column("type_prefix", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("app", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("schema_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("namespace", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("project", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("custom_fields", sa.JSON(), nullable=True),
        sa.Column("ownership", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace", "app", "name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("intake_tasks")
    op.drop_table("intake_export_jobs")
    op.drop_table("intake_entries")
    op.drop_table("intake_apps")
    # ### end Alembic commands ###
