{{- if .Values.api.enabled }}
{{- if .Values.api.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nmp-api.apiServiceAccountName" . }}
  labels:
    app.kubernetes.io/component: nmp-api
    {{- include "nemo-platform.labels" . | nindent 4 }}
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.api.serviceAccount.automount }}
{{- end }}
{{- end }}
