{{- if .Values.api.enabled }}
{{- if .Values.api.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nmp-api.api-servicename" . }}
  labels:
    app.kubernetes.io/component: nmp-api
    {{- include "nemo-platform.labels" . | nindent 4 }}
  {{- with .Values.api.podDisruptionBudget.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: nmp-api
      {{- include "nemo-platform.selectorLabels" . | nindent 6 }}
  {{- if .Values.api.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.api.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable | default 1 }}
  {{- end }}
{{- end }}
{{- end }}
