apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nemo-platform.platform-configmap" . }}
  labels:
    {{- include "nemo-platform.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ include "nemo-platform.calculatedConfig" . | nindent 4 }}
