# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Generated from k8s-nim-operator v2.0.2
# Source: https://github.com/NVIDIA/k8s-nim-operator
# generated by datamodel-codegen:
#   filename:  temp_schema.json
#   timestamp: 2025-10-24T18:28:58+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Optional, Union

from pydantic import AwareDatetime, BaseModel, Field, RootModel


class CertConfig(BaseModel):
    """
    CertConfig is the name of the ConfigMap containing the custom certificates.
    for secure communication.
    Deprecated: use `Proxy` instead to configure custom certificates for using proxy.
    """

    mountPath: str = Field(
        ...,
        description="MountPath is the path where the certificates should be mounted in the container.",
    )
    name: str = Field(..., description="Name of the ConfigMap containing the certificate data.")


class ConfigMapKeyRef(BaseModel):
    """
    Selects a key of a ConfigMap.
    """

    key: str = Field(..., description="The key to select.")
    name: Optional[str] = Field(
        "",
        description="Name of the referent.\nThis field is effectively required, but due to backwards compatibility is\nallowed to be empty. Instances of this type with an empty value here are\nalmost certainly wrong.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names",
    )
    optional: Optional[bool] = Field(None, description="Specify whether the ConfigMap or its key must be defined")


class FieldRef(BaseModel):
    """
    Selects a field of the pod: supports metadata.name, metadata.namespace, `metadata.labels['<KEY>']`, `metadata.annotations['<KEY>']`,
    spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.
    """

    apiVersion: Optional[str] = Field(
        None,
        description='Version of the schema the FieldPath is written in terms of, defaults to "v1".',
    )
    fieldPath: str = Field(..., description="Path of the field to select in the specified API version.")


class Divisor(RootModel[int]):
    root: int


class Divisor1(RootModel[str]):
    root: str


class ResourceFieldRef(BaseModel):
    """
    Selects a resource of the container: only resources limits and requests
    (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.
    """

    containerName: Optional[str] = Field(
        None, description="Container name: required for volumes, optional for env vars"
    )
    divisor: Optional[Union[Divisor, Divisor1]] = Field(
        None,
        description='Specifies the output format of the exposed resources, defaults to "1"',
    )
    resource: str = Field(..., description="Required: resource to select")


class SecretKeyRef(BaseModel):
    """
    Selects a key of a secret in the pod's namespace
    """

    key: str = Field(
        ...,
        description="The key of the secret to select from.  Must be a valid secret key.",
    )
    name: Optional[str] = Field(
        "",
        description="Name of the referent.\nThis field is effectively required, but due to backwards compatibility is\nallowed to be empty. Instances of this type with an empty value here are\nalmost certainly wrong.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names",
    )
    optional: Optional[bool] = Field(None, description="Specify whether the Secret or its key must be defined")


class ValueFrom(BaseModel):
    """
    Source for the environment variable's value. Cannot be used if value is not empty.
    """

    configMapKeyRef: Optional[ConfigMapKeyRef] = Field(None, description="Selects a key of a ConfigMap.")
    fieldRef: Optional[FieldRef] = Field(
        None,
        description="Selects a field of the pod: supports metadata.name, metadata.namespace, `metadata.labels['<KEY>']`, `metadata.annotations['<KEY>']`,\nspec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.",
    )
    resourceFieldRef: Optional[ResourceFieldRef] = Field(
        None,
        description="Selects a resource of the container: only resources limits and requests\n(limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.",
    )
    secretKeyRef: Optional[SecretKeyRef] = Field(None, description="Selects a key of a secret in the pod's namespace")


class EnvItem(BaseModel):
    """
    EnvVar represents an environment variable present in a Container.
    """

    name: str = Field(..., description="Name of the environment variable. Must be a C_IDENTIFIER.")
    value: Optional[str] = Field(
        None,
        description='Variable references $(VAR_NAME) are expanded\nusing the previously defined environment variables in the container and\nany service environment variables. If a variable cannot be resolved,\nthe reference in the input string will be unchanged. Double $$ are reduced\nto a single $, which allows for escaping the $(VAR_NAME) syntax: i.e.\n"$$(VAR_NAME)" will produce the string literal "$(VAR_NAME)".\nEscaped references will never be expanded, regardless of whether the variable\nexists or not.\nDefaults to "".',
    )
    valueFrom: Optional[ValueFrom] = Field(
        None,
        description="Source for the environment variable's value. Cannot be used if value is not empty.",
    )


class Proxy(BaseModel):
    """
    ProxySpec defines the proxy configuration for NIMService.
    """

    certConfigMap: Optional[str] = None
    httpProxy: Optional[str] = None
    httpsProxy: Optional[str] = None
    noProxy: Optional[str] = None


class Cpu(RootModel[int]):
    root: int


class Cpu1(RootModel[str]):
    root: str


class Memory(RootModel[int]):
    root: int


class Memory1(RootModel[str]):
    root: str


class Resources(BaseModel):
    """
    Resources defines the minimum resources required for the caching job to run(cpu, memory, gpu).
    """

    cpu: Optional[Union[Cpu, Cpu1]] = Field(
        None,
        description="CPU indicates the minimum number of CPUs to use while caching NIM",
    )
    memory: Optional[Union[Memory, Memory1]] = Field(
        None,
        description='Memory indicates the minimum amount of memory to use while caching NIM\nValid values are numbers followed by one of the suffixes Ki, Mi, Gi, or Ti (e.g. "4Gi", "4096Mi").',
    )


class DataStore(BaseModel):
    """
    DataStore represents models stored in NVIDIA NeMo DataStore service
    """

    authSecret: str = Field(
        ...,
        description='AuthSecret is the name of the secret containing the "HF_TOKEN" token',
        min_length=1,
    )
    datasetName: Optional[str] = Field(None, description="DatasetName is the name of the dataset")
    endpoint: str = Field(
        ...,
        description="Endpoint is the HuggingFace endpoint from NeMo DataStore",
        pattern="^https?://.*/v1/hf/?$",
    )
    modelName: Optional[str] = Field(None, description="ModelName is the name of the model")
    modelPuller: str = Field(
        ...,
        description="ModelPuller is the containerized huggingface-cli image to pull the data",
        min_length=1,
    )
    namespace: str = Field(..., description="Namespace is the namespace within NeMo DataStore")
    pullSecret: str = Field(
        ...,
        description="PullSecret is the name of the image pull secret for the modelPuller image",
        min_length=1,
    )
    revision: Optional[str] = Field(
        None,
        description="Revision is the revision of the object to be cached. This is either a commit hash, branch name or tag.",
        min_length=1,
    )


class Hf(BaseModel):
    """
    HuggingFaceHub represents models stored in HuggingFace Hub
    """

    authSecret: str = Field(
        ...,
        description='AuthSecret is the name of the secret containing the "HF_TOKEN" token',
        min_length=1,
    )
    datasetName: Optional[str] = Field(None, description="DatasetName is the name of the dataset")
    endpoint: str = Field(..., description="Endpoint is the HuggingFace endpoint", pattern="^https?://.*$")
    modelName: Optional[str] = Field(None, description="ModelName is the name of the model")
    modelPuller: str = Field(
        ...,
        description="ModelPuller is the containerized huggingface-cli image to pull the data",
        min_length=1,
    )
    namespace: str = Field(
        ...,
        description="Namespace is the namespace within the HuggingFace Hub",
        min_length=1,
    )
    pullSecret: str = Field(
        ...,
        description="PullSecret is the name of the image pull secret for the modelPuller image",
        min_length=1,
    )
    revision: Optional[str] = Field(
        None,
        description="Revision is the revision of the object to be cached. This is either a commit hash, branch name or tag.",
        min_length=1,
    )


class Gpu(BaseModel):
    """
    GPUSpec is the spec required to cache models for selected gpu type.
    """

    ids: Optional[list[str]] = Field(None, description="IDs are the device-ids for a specific GPU SKU")
    product: Optional[str] = Field(None, description="Product is the GPU product string (h100, a100, l40s)")


class Model(BaseModel):
    """
    Model spec for caching
    """

    buildable: Optional[bool] = Field(
        None,
        description="Buildable indicates generic model profiles that can be optimized with an NVIDIA engine for any GPUs",
    )
    engine: Optional[str] = Field(None, description="Engine is the backend engine (tensorrt_llm, vllm)")
    gpus: Optional[list[Gpu]] = Field(
        None,
        description="GPU is the spec for matching GPUs for caching optimized models",
    )
    lora: Optional[bool] = Field(None, description="Lora indicates a finetuned model with LoRa adapters")
    precision: Optional[str] = Field(None, description="Precision is the precision for model quantization")
    profiles: Optional[list[str]] = Field(
        None,
        description="Profiles are the specific model profiles to cache. When these are provided, rest of the model parameters for profile selection are ignored",
    )
    qosProfile: Optional[str] = Field(
        None,
        description="QoSProfile is the supported QoS profile types for the models (throughput, latency)",
    )
    tensorParallelism: Optional[str] = Field(
        None,
        description="TensorParallelism is the minimum GPUs required for the model computations",
    )


class Ngc(BaseModel):
    """
    NGCSource represents models stored in NGC
    """

    authSecret: str = Field(
        ...,
        description="The name of an existing pull secret containing the NGC_API_KEY",
    )
    model: Optional[Model] = Field(None, description="Model spec for caching")
    modelPuller: str = Field(..., description="ModelPuller is the container image that can pull the model")
    pullSecret: Optional[str] = Field(None, description="PullSecret to pull the model puller image")


class Source(BaseModel):
    """
    Source is the NIM model source to cache
    """

    dataStore: Optional[DataStore] = Field(
        None,
        description="DataStore represents models stored in NVIDIA NeMo DataStore service",
    )
    hf: Optional[Hf] = Field(None, description="HuggingFaceHub represents models stored in HuggingFace Hub")
    ngc: Optional[Ngc] = Field(None, description="NGCSource represents models stored in NGC")


class Pvc(BaseModel):
    """
    PersistentVolumeClaim is the pvc volume used for caching NIM
    """

    annotations: Optional[dict[str, str]] = Field(None, description="Annotations for the PVC")
    create: Optional[bool] = Field(
        None,
        description="Create specifies whether to create a new PersistentVolumeClaim (PVC).\nIf set to false, an existing PVC must be referenced via the `Name` field.",
    )
    name: Optional[str] = Field(
        None,
        description="Name of the PVC to use. Required if `Create` is false (i.e., using an existing PVC).",
    )
    size: Optional[str] = Field(None, description="Size of the NIM cache in Gi, used during PVC creation")
    storageClass: Optional[str] = Field(
        None,
        description="StorageClass to be used for PVC creation. Leave it as empty if the PVC is already created or\na default storage class is set in the cluster.",
    )
    subPath: Optional[str] = Field(None, description="SubPath is the path inside the PVC that should be mounted")
    volumeAccessMode: Optional[str] = Field(None, description="VolumeAccessMode is the volume access mode of the PVC")


class Storage(BaseModel):
    """
    Storage is the target storage for caching NIM model
    """

    hostPath: Optional[str] = Field(
        None,
        description="HostPath is the host path volume for caching NIM\n\nDeprecated: use PVC instead.",
    )
    pvc: Optional[Pvc] = Field(None, description="PersistentVolumeClaim is the pvc volume used for caching NIM")


class Toleration(BaseModel):
    """
    The pod this Toleration is attached to tolerates any taint that matches
    the triple <key,value,effect> using the matching operator <operator>.
    """

    effect: Optional[str] = Field(
        None,
        description="Effect indicates the taint effect to match. Empty means match all taint effects.\nWhen specified, allowed values are NoSchedule, PreferNoSchedule and NoExecute.",
    )
    key: Optional[str] = Field(
        None,
        description="Key is the taint key that the toleration applies to. Empty means match all taint keys.\nIf the key is empty, operator must be Exists; this combination means to match all values and all keys.",
    )
    operator: Optional[str] = Field(
        None,
        description="Operator represents a key's relationship to the value.\nValid operators are Exists and Equal. Defaults to Equal.\nExists is equivalent to wildcard for value, so that a pod can\ntolerate all taints of a particular category.",
    )
    tolerationSeconds: Optional[int] = Field(
        None,
        description="TolerationSeconds represents the period of time the toleration (which must be\nof effect NoExecute, otherwise this field is ignored) tolerates the taint. By default,\nit is not set, which means tolerate the taint forever (do not evict). Zero and\nnegative values will be treated as 0 (evict immediately) by the system.",
    )
    value: Optional[str] = Field(
        None,
        description="Value is the taint value the toleration matches to.\nIf the operator is Exists, the value should be empty, otherwise just a regular string.",
    )


class Spec(BaseModel):
    """
    NIMCacheSpec defines the desired state of NIMCache.
    """

    certConfig: Optional[CertConfig] = Field(
        None,
        description="CertConfig is the name of the ConfigMap containing the custom certificates.\nfor secure communication.\nDeprecated: use `Proxy` instead to configure custom certificates for using proxy.",
    )
    env: Optional[list[EnvItem]] = Field(
        None,
        description="Env are the additional custom environment variabes for the caching job",
    )
    groupID: Optional[int] = Field(None, description="GroupID is the group ID for the caching job")
    nodeSelector: Optional[dict[str, str]] = Field(
        None,
        description="NodeSelector is the node selector labels to schedule the caching job.",
    )
    proxy: Optional[Proxy] = Field(None, description="ProxySpec defines the proxy configuration for NIMService.")
    resources: Optional[Resources] = Field(
        None,
        description="Resources defines the minimum resources required for the caching job to run(cpu, memory, gpu).",
    )
    runtimeClassName: Optional[str] = Field(
        None, description="RuntimeClassName is the runtimeclass for the caching job"
    )
    source: Source = Field(..., description="Source is the NIM model source to cache")
    storage: Storage = Field(..., description="Storage is the target storage for caching NIM model")
    tolerations: Optional[list[Toleration]] = Field(
        None, description="Tolerations for running the job to cache the NIM model"
    )
    userID: Optional[int] = Field(None, description="UserID is the user ID for the caching job")

    initContainers: Optional[list[ContainerSpec]] = Field(None, description="Init containers to add to the NIMCache")


class Image(BaseModel):
    """
    Image defines image attributes.
    """

    pullPolicy: Optional[str] = None
    pullSecrets: Optional[list[str]] = None
    repository: str
    tag: str


class ContainerSpec(BaseModel):
    """
    ContainerSpec defines a container specification for init containers.
    """

    name: str = Field(..., description="Name of the container")
    image: Image = Field(..., description="Image defines image attributes.")
    command: Optional[list[str]] = Field(None, description="Command to execute in the container")
    args: Optional[list[str]] = Field(None, description="Arguments to pass to the command")
    env: Optional[list[EnvItem]] = Field(None, description="Environment variables for the container")
    workingDir: Optional[str] = Field(None, description="Working directory for the container")


class Status1(Enum):
    """
    status of the condition, one of True, False, Unknown.
    """

    True_ = "True"
    False_ = "False"
    Unknown = "Unknown"


class Condition(BaseModel):
    """
    Condition contains details for one aspect of the current state of this API Resource.
    """

    lastTransitionTime: AwareDatetime = Field(
        ...,
        description="lastTransitionTime is the last time the condition transitioned from one status to another.\nThis should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.",
    )
    message: str = Field(
        ...,
        description="message is a human readable message indicating details about the transition.\nThis may be an empty string.",
        max_length=32768,
    )
    observedGeneration: Optional[int] = Field(
        None,
        description="observedGeneration represents the .metadata.generation that the condition was set based upon.\nFor instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date\nwith respect to the current state of the instance.",
        ge=0,
    )
    reason: str = Field(
        ...,
        description="reason contains a programmatic identifier indicating the reason for the condition's last transition.\nProducers of specific condition types may define expected values and meanings for this field,\nand whether the values are considered a guaranteed API.\nThe value should be a CamelCase string.\nThis field may not be empty.",
        max_length=1024,
        min_length=1,
        pattern="^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$",
    )
    status: Status1 = Field(..., description="status of the condition, one of True, False, Unknown.")
    type: str = Field(
        ...,
        description="type of condition in CamelCase or in foo.example.com/CamelCase.",
        max_length=316,
        pattern="^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$",
    )


class Profile(BaseModel):
    """
    NIMProfile defines the profiles that were cached.
    """

    config: Optional[dict[str, str]] = None
    model: Optional[str] = None
    name: Optional[str] = None
    release: Optional[str] = None


class Status(BaseModel):
    """
    NIMCacheStatus defines the observed state of NIMCache.
    """

    conditions: Optional[list[Condition]] = None
    profiles: Optional[list[Profile]] = None
    pvc: Optional[str] = None
    state: Optional[str] = None


class NIMCache(BaseModel):
    """
    NIMCache is the Schema for the nimcaches API.
    """

    apiVersion: Optional[str] = Field(
        None,
        description="APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
    )
    kind: Optional[str] = Field(
        None,
        description="Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
    )
    metadata: Optional[dict[str, Any]] = None
    spec: Optional[Spec] = Field(None, description="NIMCacheSpec defines the desired state of NIMCache.")
    status: Optional[Status] = Field(None, description="NIMCacheStatus defines the observed state of NIMCache.")
