# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Generated from k8s-nim-operator v2.0.2
# Source: https://github.com/NVIDIA/k8s-nim-operator
# generated by datamodel-codegen:
#   filename:  temp_schema.json
#   timestamp: 2025-10-24T18:28:57+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Optional, Union

from pydantic import AwareDatetime, BaseModel, Field, RootModel


class ConfigMapKeyRef(BaseModel):
    """
    Selects a key of a ConfigMap.
    """

    key: str = Field(..., description="The key to select.")
    name: Optional[str] = Field(
        "",
        description="Name of the referent.\nThis field is effectively required, but due to backwards compatibility is\nallowed to be empty. Instances of this type with an empty value here are\nalmost certainly wrong.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names",
    )
    optional: Optional[bool] = Field(None, description="Specify whether the ConfigMap or its key must be defined")


class FieldRef(BaseModel):
    """
    Selects a field of the pod: supports metadata.name, metadata.namespace, `metadata.labels['<KEY>']`, `metadata.annotations['<KEY>']`,
    spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.
    """

    apiVersion: Optional[str] = Field(
        None,
        description='Version of the schema the FieldPath is written in terms of, defaults to "v1".',
    )
    fieldPath: str = Field(..., description="Path of the field to select in the specified API version.")


class Divisor(RootModel[int]):
    root: int


class Divisor1(RootModel[str]):
    root: str


class ResourceFieldRef(BaseModel):
    """
    Selects a resource of the container: only resources limits and requests
    (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.
    """

    containerName: Optional[str] = Field(
        None, description="Container name: required for volumes, optional for env vars"
    )
    divisor: Optional[Union[Divisor, Divisor1]] = Field(
        None,
        description='Specifies the output format of the exposed resources, defaults to "1"',
    )
    resource: str = Field(..., description="Required: resource to select")


class SecretKeyRef(BaseModel):
    """
    Selects a key of a secret in the pod's namespace
    """

    key: str = Field(
        ...,
        description="The key of the secret to select from.  Must be a valid secret key.",
    )
    name: Optional[str] = Field(
        "",
        description="Name of the referent.\nThis field is effectively required, but due to backwards compatibility is\nallowed to be empty. Instances of this type with an empty value here are\nalmost certainly wrong.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names",
    )
    optional: Optional[bool] = Field(None, description="Specify whether the Secret or its key must be defined")


class ValueFrom(BaseModel):
    """
    Source for the environment variable's value. Cannot be used if value is not empty.
    """

    configMapKeyRef: Optional[ConfigMapKeyRef] = Field(None, description="Selects a key of a ConfigMap.")
    fieldRef: Optional[FieldRef] = Field(
        None,
        description="Selects a field of the pod: supports metadata.name, metadata.namespace, `metadata.labels['<KEY>']`, `metadata.annotations['<KEY>']`,\nspec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.",
    )
    resourceFieldRef: Optional[ResourceFieldRef] = Field(
        None,
        description="Selects a resource of the container: only resources limits and requests\n(limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.",
    )
    secretKeyRef: Optional[SecretKeyRef] = Field(None, description="Selects a key of a secret in the pod's namespace")


class EnvItem(BaseModel):
    """
    EnvVar represents an environment variable present in a Container.
    """

    name: str = Field(..., description="Name of the environment variable. Must be a C_IDENTIFIER.")
    value: Optional[str] = Field(
        None,
        description='Variable references $(VAR_NAME) are expanded\nusing the previously defined environment variables in the container and\nany service environment variables. If a variable cannot be resolved,\nthe reference in the input string will be unchanged. Double $$ are reduced\nto a single $, which allows for escaping the $(VAR_NAME) syntax: i.e.\n"$$(VAR_NAME)" will produce the string literal "$(VAR_NAME)".\nEscaped references will never be expanded, regardless of whether the variable\nexists or not.\nDefaults to "".',
    )
    valueFrom: Optional[ValueFrom] = Field(
        None,
        description="Source for the environment variable's value. Cannot be used if value is not empty.",
    )


class Resource(BaseModel):
    """
    resource is an ObjectRef to another Kubernetes resource in the namespace
    of the Ingress object. If resource is specified, a service.Name and
    service.Port must not be specified.
    This is a mutually exclusive setting with "Service".
    """

    apiGroup: Optional[str] = Field(
        None,
        description="APIGroup is the group for the resource being referenced.\nIf APIGroup is not specified, the specified Kind must be in the core API group.\nFor any other third-party types, APIGroup is required.",
    )
    kind: str = Field(..., description="Kind is the type of resource being referenced")
    name: str = Field(..., description="Name is the name of resource being referenced")


class Port(BaseModel):
    """
    port of the referenced service. A port name or port number
    is required for a IngressServiceBackend.
    """

    name: Optional[str] = Field(
        None,
        description='name is the name of the port on the Service.\nThis is a mutually exclusive setting with "Number".',
    )
    number: Optional[int] = Field(
        None,
        description='number is the numerical port number (e.g. 80) on the Service.\nThis is a mutually exclusive setting with "Name".',
    )


class Service(BaseModel):
    """
    service references a service as a backend.
    This is a mutually exclusive setting with "Resource".
    """

    name: str = Field(
        ...,
        description="name is the referenced service. The service must exist in\nthe same namespace as the Ingress object.",
    )
    port: Optional[Port] = Field(
        None,
        description="port of the referenced service. A port name or port number\nis required for a IngressServiceBackend.",
    )


class DefaultBackend(BaseModel):
    """
    defaultBackend is the backend that should handle requests that don't
    match any rule. If Rules are not specified, DefaultBackend must be specified.
    If DefaultBackend is not set, the handling of requests that do not match any
    of the rules will be up to the Ingress controller.
    """

    resource: Optional[Resource] = Field(
        None,
        description='resource is an ObjectRef to another Kubernetes resource in the namespace\nof the Ingress object. If resource is specified, a service.Name and\nservice.Port must not be specified.\nThis is a mutually exclusive setting with "Service".',
    )
    service: Optional[Service] = Field(
        None,
        description='service references a service as a backend.\nThis is a mutually exclusive setting with "Resource".',
    )


class Service1(BaseModel):
    """
    service references a service as a backend.
    This is a mutually exclusive setting with "Resource".
    """

    name: str = Field(
        ...,
        description="name is the referenced service. The service must exist in\nthe same namespace as the Ingress object.",
    )
    port: Optional[Port] = Field(
        None,
        description="port of the referenced service. A port name or port number\nis required for a IngressServiceBackend.",
    )


class Backend(BaseModel):
    """
    backend defines the referenced service endpoint to which the traffic
    will be forwarded to.
    """

    resource: Optional[Resource] = Field(
        None,
        description='resource is an ObjectRef to another Kubernetes resource in the namespace\nof the Ingress object. If resource is specified, a service.Name and\nservice.Port must not be specified.\nThis is a mutually exclusive setting with "Service".',
    )
    service: Optional[Service1] = Field(
        None,
        description='service references a service as a backend.\nThis is a mutually exclusive setting with "Resource".',
    )


class Path(BaseModel):
    """
    HTTPIngressPath associates a path with a backend. Incoming urls matching the
    path are forwarded to the backend.
    """

    backend: Backend = Field(
        ...,
        description="backend defines the referenced service endpoint to which the traffic\nwill be forwarded to.",
    )
    path: Optional[str] = Field(
        None,
        description='path is matched against the path of an incoming request. Currently it can\ncontain characters disallowed from the conventional "path" part of a URL\nas defined by RFC 3986. Paths must begin with a \'/\' and must be present\nwhen using PathType with value "Exact" or "Prefix".',
    )
    pathType: str = Field(
        ...,
        description="pathType determines the interpretation of the path matching. PathType can\nbe one of the following values:\n* Exact: Matches the URL path exactly.\n* Prefix: Matches based on a URL path prefix split by '/'. Matching is\n  done on a path element by element basis. A path element refers is the\n  list of labels in the path split by the '/' separator. A request is a\n  match for path p if every p is an element-wise prefix of p of the\n  request path. Note that if the last element of the path is a substring\n  of the last element in request path, it is not a match (e.g. /foo/bar\n  matches /foo/bar/baz, but does not match /foo/barbaz).\n* ImplementationSpecific: Interpretation of the Path matching is up to\n  the IngressClass. Implementations can treat this as a separate PathType\n  or treat it identically to Prefix or Exact path types.\nImplementations are required to support all path types.",
    )


class Http(BaseModel):
    """
    HTTPIngressRuleValue is a list of http selectors pointing to backends.
    In the example: http://<host>/<path>?<searchpart> -> backend where
    where parts of the url correspond to RFC 3986, this resource will be used
    to match against everything after the last '/' and before the first '?'
    or '#'.
    """

    paths: list[Path] = Field(..., description="paths is a collection of paths that map requests to backends.")


class Rule(BaseModel):
    """
    IngressRule represents the rules mapping the paths under a specified host to
    the related backend services. Incoming requests are first evaluated for a host
    match, then routed to the backend associated with the matching IngressRuleValue.
    """

    host: Optional[str] = Field(
        None,
        description='host is the fully qualified domain name of a network host, as defined by RFC 3986.\nNote the following deviations from the "host" part of the\nURI as defined in RFC 3986:\n1. IPs are not allowed. Currently an IngressRuleValue can only apply to\n   the IP in the Spec of the parent Ingress.\n2. The `:` delimiter is not respected because ports are not allowed.\n\t  Currently the port of an Ingress is implicitly :80 for http and\n\t  :443 for https.\nBoth these may change in the future.\nIncoming requests are matched against the host before the\nIngressRuleValue. If the host is unspecified, the Ingress routes all\ntraffic based on the specified IngressRuleValue.\n\nhost can be "precise" which is a domain name without the terminating dot of\na network host (e.g. "foo.bar.com") or "wildcard", which is a domain name\nprefixed with a single wildcard label (e.g. "*.foo.com").\nThe wildcard character \'*\' must appear by itself as the first DNS label and\nmatches only a single label. You cannot have a wildcard label by itself (e.g. Host == "*").\nRequests will be matched against the Host field in the following way:\n1. If host is precise, the request matches this rule if the http host header is equal to Host.\n2. If host is a wildcard, then the request matches this rule if the http host header\nis to equal to the suffix (removing the first label) of the wildcard rule.',
    )
    http: Optional[Http] = Field(
        None,
        description="HTTPIngressRuleValue is a list of http selectors pointing to backends.\nIn the example: http://<host>/<path>?<searchpart> -> backend where\nwhere parts of the url correspond to RFC 3986, this resource will be used\nto match against everything after the last '/' and before the first '?'\nor '#'.",
    )


class Tl(BaseModel):
    """
    IngressTLS describes the transport layer security associated with an ingress.
    """

    hosts: Optional[list[str]] = Field(
        None,
        description="hosts is a list of hosts included in the TLS certificate. The values in\nthis list must match the name/s used in the tlsSecret. Defaults to the\nwildcard host setting for the loadbalancer controller fulfilling this\nIngress, if left unspecified.",
    )
    secretName: Optional[str] = Field(
        None,
        description='secretName is the name of the secret used to terminate TLS traffic on\nport 443. Field is left optional to allow TLS routing based on SNI\nhostname alone. If the SNI host in a listener conflicts with the "Host"\nheader field used by an IngressRule, the SNI host is used for termination\nand value of the "Host" header is used for routing.',
    )


class Spec1(BaseModel):
    """
    IngressSpec describes the Ingress the user wishes to exist.
    """

    defaultBackend: Optional[DefaultBackend] = Field(
        None,
        description="defaultBackend is the backend that should handle requests that don't\nmatch any rule. If Rules are not specified, DefaultBackend must be specified.\nIf DefaultBackend is not set, the handling of requests that do not match any\nof the rules will be up to the Ingress controller.",
    )
    ingressClassName: Optional[str] = Field(
        None,
        description="ingressClassName is the name of an IngressClass cluster resource. Ingress\ncontroller implementations use this field to know whether they should be\nserving this Ingress resource, by a transitive connection\n(controller -> IngressClass -> Ingress resource). Although the\n`kubernetes.io/ingress.class` annotation (simple constant name) was never\nformally defined, it was widely supported by Ingress controllers to create\na direct binding between Ingress controller and Ingress resources. Newly\ncreated Ingress resources should prefer using the field. However, even\nthough the annotation is officially deprecated, for backwards compatibility\nreasons, ingress controllers should still honor that annotation if present.",
    )
    rules: Optional[list[Rule]] = Field(
        None,
        description="rules is a list of host rules used to configure the Ingress. If unspecified,\nor no rule matches, all traffic is sent to the default backend.",
    )
    tls: Optional[list[Tl]] = Field(
        None,
        description="tls represents the TLS configuration. Currently the Ingress only supports a\nsingle TLS port, 443. If multiple members of this list specify different hosts,\nthey will be multiplexed on the same port according to the hostname specified\nthrough the SNI TLS extension, if the ingress controller fulfilling the\ningress supports SNI.",
    )


class Ingress(BaseModel):
    """
    Ingress defines attributes to enable ingress for the service.
    """

    annotations: Optional[dict[str, str]] = None
    enabled: Optional[bool] = Field(None, description="ingress, or virtualService - not both")
    spec: Optional[Spec1] = Field(None, description="IngressSpec describes the Ingress the user wishes to exist.")


class Service2(BaseModel):
    """
    Service defines attributes to create a service.
    """

    annotations: Optional[dict[str, str]] = None
    grpcPort: Optional[int] = Field(
        None,
        description="GRPCPort is the GRPC serving port\nNote: This port is only applicable for NIMs that runs a Triton GRPC Inference Server.",
        ge=1,
        le=65535,
    )
    metricsPort: Optional[int] = Field(
        None,
        description="MetricsPort is the port for metrics\nNote: This port is only applicable for NIMs that runs a separate metrics endpoint on Triton Inference Server.",
        ge=1,
        le=65535,
    )
    name: Optional[str] = Field(None, description="Override the default service name")
    port: Optional[int] = Field(
        8000,
        description="Port is the main api serving port (default: 8000)",
        ge=1,
        le=65535,
    )
    type: Optional[str] = Field(None, description="Service Type string describes ingress methods for a service")


class Expose(BaseModel):
    """
    Expose defines attributes to expose the service.
    """

    ingress: Optional[Ingress] = Field(
        None,
        description="Ingress defines attributes to enable ingress for the service.",
    )
    service: Optional[Service2] = Field(None, description="Service defines attributes to create a service.")


class Image(BaseModel):
    """
    Image defines image attributes.
    """

    pullPolicy: Optional[str] = None
    pullSecrets: Optional[list[str]] = None
    repository: str
    tag: str


class Exec(BaseModel):
    """
    Exec specifies the action to take.
    """

    command: Optional[list[str]] = Field(
        None,
        description="Command is the command line to execute inside the container, the working directory for the\ncommand  is root ('/') in the container's filesystem. The command is simply exec'd, it is\nnot run inside a shell, so traditional shell instructions ('|', etc) won't work. To use\na shell, you need to explicitly call out to that shell.\nExit status of 0 is treated as live/healthy and non-zero is unhealthy.",
    )


class Grpc(BaseModel):
    """
    GRPC specifies an action involving a GRPC port.
    """

    port: int = Field(
        ...,
        description="Port number of the gRPC service. Number must be in the range 1 to 65535.",
    )
    service: Optional[str] = Field(
        "",
        description="Service is the name of the service to place in the gRPC HealthCheckRequest\n(see https://github.com/grpc/grpc/blob/master/doc/health-checking.md).\n\nIf this is not specified, the default behavior is defined by gRPC.",
    )


class HttpHeader(BaseModel):
    """
    HTTPHeader describes a custom header to be used in HTTP probes
    """

    name: str = Field(
        ...,
        description="The header field name.\nThis will be canonicalized upon output, so case-variant names will be understood as the same header.",
    )
    value: str = Field(..., description="The header field value")


class HttpGet(BaseModel):
    """
    HTTPGet specifies the http request to perform.
    """

    host: Optional[str] = Field(
        None,
        description='Host name to connect to, defaults to the pod IP. You probably want to set\n"Host" in httpHeaders instead.',
    )
    httpHeaders: Optional[list[HttpHeader]] = Field(
        None,
        description="Custom headers to set in the request. HTTP allows repeated headers.",
    )
    path: Optional[str] = Field(None, description="Path to access on the HTTP server.")
    port: Union[int, str] = Field(
        ...,
        description="Name or number of the port to access on the container.\nNumber must be in the range 1 to 65535.\nName must be an IANA_SVC_NAME.",
    )
    scheme: Optional[str] = Field(None, description="Scheme to use for connecting to the host.\nDefaults to HTTP.")


class TcpSocket(BaseModel):
    """
    TCPSocket specifies an action involving a TCP port.
    """

    host: Optional[str] = Field(None, description="Optional: Host name to connect to, defaults to the pod IP.")
    port: Union[int, str] = Field(
        ...,
        description="Number or name of the port to access on the container.\nNumber must be in the range 1 to 65535.\nName must be an IANA_SVC_NAME.",
    )


class Probe(BaseModel):
    """
    Probe describes a health check to be performed against a container to determine whether it is
    alive or ready to receive traffic.
    """

    exec: Optional[Exec] = Field(None, description="Exec specifies the action to take.")
    failureThreshold: Optional[int] = Field(
        None,
        description="Minimum consecutive failures for the probe to be considered failed after having succeeded.\nDefaults to 3. Minimum value is 1.",
    )
    grpc: Optional[Grpc] = Field(None, description="GRPC specifies an action involving a GRPC port.")
    httpGet: Optional[HttpGet] = Field(None, description="HTTPGet specifies the http request to perform.")
    initialDelaySeconds: Optional[int] = Field(
        None,
        description="Number of seconds after the container has started before liveness probes are initiated.\nMore info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes",
    )
    periodSeconds: Optional[int] = Field(
        None,
        description="How often (in seconds) to perform the probe.\nDefault to 10 seconds. Minimum value is 1.",
    )
    successThreshold: Optional[int] = Field(
        None,
        description="Minimum consecutive successes for the probe to be considered successful after having failed.\nDefaults to 1. Must be 1 for liveness and startup. Minimum value is 1.",
    )
    tcpSocket: Optional[TcpSocket] = Field(None, description="TCPSocket specifies an action involving a TCP port.")
    terminationGracePeriodSeconds: Optional[int] = Field(
        None,
        description="Optional duration in seconds the pod needs to terminate gracefully upon probe failure.\nThe grace period is the duration in seconds after the processes running in the pod are sent\na termination signal and the time when the processes are forcibly halted with a kill signal.\nSet this value longer than the expected cleanup time for your process.\nIf this value is nil, the pod's terminationGracePeriodSeconds will be used. Otherwise, this\nvalue overrides the value provided by the pod spec.\nValue must be non-negative integer. The value zero indicates stop immediately via\nthe kill signal (no opportunity to shut down).\nThis is a beta field and requires enabling ProbeTerminationGracePeriod feature gate.\nMinimum value is 1. spec.terminationGracePeriodSeconds is used if unset.",
    )
    timeoutSeconds: Optional[int] = Field(
        None,
        description="Number of seconds after which the probe times out.\nDefaults to 1 second. Minimum value is 1.\nMore info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes",
    )


class LivenessProbe(BaseModel):
    """
    Probe defines attributes for startup/liveness/readiness probes.
    """

    enabled: Optional[bool] = None
    probe: Optional[Probe] = Field(
        None,
        description="Probe describes a health check to be performed against a container to determine whether it is\nalive or ready to receive traffic.",
    )


class ServiceMonitor(BaseModel):
    """
    for use with the Prometheus Operator and the primary service object
    """

    additionalLabels: Optional[dict[str, str]] = None
    annotations: Optional[dict[str, str]] = None
    interval: Optional[str] = Field(
        None,
        description="Duration is a valid time duration that can be parsed by Prometheus model.ParseDuration() function.\nSupported units: y, w, d, h, m, s, ms\nExamples: `30s`, `1m`, `1h20m15s`, `15d`",
        pattern="^(0|(([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?)$",
    )
    scrapeTimeout: Optional[str] = Field(
        None,
        description="Duration is a valid time duration that can be parsed by Prometheus model.ParseDuration() function.\nSupported units: y, w, d, h, m, s, ms\nExamples: `30s`, `1m`, `1h20m15s`, `15d`",
        pattern="^(0|(([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?)$",
    )


class Metrics(BaseModel):
    """
    Metrics defines attributes to setup metrics collection.
    """

    enabled: Optional[bool] = None
    serviceMonitor: Optional[ServiceMonitor] = Field(
        None,
        description="for use with the Prometheus Operator and the primary service object",
    )


class MatchExpression(BaseModel):
    """
    A label selector requirement is a selector that contains values, a key, and an operator that
    relates the key and values.
    """

    key: str = Field(..., description="key is the label key that the selector applies to.")
    operator: str = Field(
        ...,
        description="operator represents a key's relationship to a set of values.\nValid operators are In, NotIn, Exists and DoesNotExist.",
    )
    values: Optional[list[str]] = Field(
        None,
        description="values is an array of string values. If the operator is In or NotIn,\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\nthe values array must be empty. This array is replaced during a strategic\nmerge patch.",
    )


class LabelSelector(BaseModel):
    """
    A label query over a set of resources, in this case pods.
    If it's null, this PodAffinityTerm matches with no Pods.
    """

    matchExpressions: Optional[list[MatchExpression]] = Field(
        None,
        description="matchExpressions is a list of label selector requirements. The requirements are ANDed.",
    )
    matchLabels: Optional[dict[str, str]] = Field(
        None,
        description='matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\nmap is equivalent to an element of matchExpressions, whose key field is "key", the\noperator is "In", and the values array contains only "value". The requirements are ANDed.',
    )


class NamespaceSelector(BaseModel):
    """
    A label query over the set of namespaces that the term applies to.
    The term is applied to the union of the namespaces selected by this field
    and the ones listed in the namespaces field.
    null selector and null or empty namespaces list means "this pod's namespace".
    An empty selector ({}) matches all namespaces.
    """

    matchExpressions: Optional[list[MatchExpression]] = Field(
        None,
        description="matchExpressions is a list of label selector requirements. The requirements are ANDed.",
    )
    matchLabels: Optional[dict[str, str]] = Field(
        None,
        description='matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\nmap is equivalent to an element of matchExpressions, whose key field is "key", the\noperator is "In", and the values array contains only "value". The requirements are ANDed.',
    )


class PodAffinityTerm(BaseModel):
    """
    Required. A pod affinity term, associated with the corresponding weight.
    """

    labelSelector: Optional[LabelSelector] = Field(
        None,
        description="A label query over a set of resources, in this case pods.\nIf it's null, this PodAffinityTerm matches with no Pods.",
    )
    matchLabelKeys: Optional[list[str]] = Field(
        None,
        description="MatchLabelKeys is a set of pod label keys to select which pods will\nbe taken into consideration. The keys are used to lookup values from the\nincoming pod labels, those key-value labels are merged with `labelSelector` as `key in (value)`\nto select the group of existing pods which pods will be taken into consideration\nfor the incoming pod's pod (anti) affinity. Keys that don't exist in the incoming\npod labels will be ignored. The default value is empty.\nThe same key is forbidden to exist in both matchLabelKeys and labelSelector.\nAlso, matchLabelKeys cannot be set when labelSelector isn't set.\nThis is a beta field and requires enabling MatchLabelKeysInPodAffinity feature gate (enabled by default).",
    )
    mismatchLabelKeys: Optional[list[str]] = Field(
        None,
        description="MismatchLabelKeys is a set of pod label keys to select which pods will\nbe taken into consideration. The keys are used to lookup values from the\nincoming pod labels, those key-value labels are merged with `labelSelector` as `key notin (value)`\nto select the group of existing pods which pods will be taken into consideration\nfor the incoming pod's pod (anti) affinity. Keys that don't exist in the incoming\npod labels will be ignored. The default value is empty.\nThe same key is forbidden to exist in both mismatchLabelKeys and labelSelector.\nAlso, mismatchLabelKeys cannot be set when labelSelector isn't set.\nThis is a beta field and requires enabling MatchLabelKeysInPodAffinity feature gate (enabled by default).",
    )
    namespaceSelector: Optional[NamespaceSelector] = Field(
        None,
        description='A label query over the set of namespaces that the term applies to.\nThe term is applied to the union of the namespaces selected by this field\nand the ones listed in the namespaces field.\nnull selector and null or empty namespaces list means "this pod\'s namespace".\nAn empty selector ({}) matches all namespaces.',
    )
    namespaces: Optional[list[str]] = Field(
        None,
        description='namespaces specifies a static list of namespace names that the term applies to.\nThe term is applied to the union of the namespaces listed in this field\nand the ones selected by namespaceSelector.\nnull or empty namespaces list and null namespaceSelector means "this pod\'s namespace".',
    )
    topologyKey: str = Field(
        ...,
        description="This pod should be co-located (affinity) or not co-located (anti-affinity) with the pods matching\nthe labelSelector in the specified namespaces, where co-located is defined as running on a node\nwhose value of the label with key topologyKey matches that of any node on which any of the\nselected pods is running.\nEmpty topologyKey is not allowed.",
    )


class PreferredDuringSchedulingIgnoredDuringExecutionItem(BaseModel):
    """
    The weights of all of the matched WeightedPodAffinityTerm fields are added per-node to find the most preferred node(s)
    """

    podAffinityTerm: PodAffinityTerm = Field(
        ...,
        description="Required. A pod affinity term, associated with the corresponding weight.",
    )
    weight: int = Field(
        ...,
        description="weight associated with matching the corresponding podAffinityTerm,\nin the range 1-100.",
    )


class LabelSelector1(BaseModel):
    """
    A label query over a set of resources, in this case pods.
    If it's null, this PodAffinityTerm matches with no Pods.
    """

    matchExpressions: Optional[list[MatchExpression]] = Field(
        None,
        description="matchExpressions is a list of label selector requirements. The requirements are ANDed.",
    )
    matchLabels: Optional[dict[str, str]] = Field(
        None,
        description='matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\nmap is equivalent to an element of matchExpressions, whose key field is "key", the\noperator is "In", and the values array contains only "value". The requirements are ANDed.',
    )


class NamespaceSelector1(BaseModel):
    """
    A label query over the set of namespaces that the term applies to.
    The term is applied to the union of the namespaces selected by this field
    and the ones listed in the namespaces field.
    null selector and null or empty namespaces list means "this pod's namespace".
    An empty selector ({}) matches all namespaces.
    """

    matchExpressions: Optional[list[MatchExpression]] = Field(
        None,
        description="matchExpressions is a list of label selector requirements. The requirements are ANDed.",
    )
    matchLabels: Optional[dict[str, str]] = Field(
        None,
        description='matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\nmap is equivalent to an element of matchExpressions, whose key field is "key", the\noperator is "In", and the values array contains only "value". The requirements are ANDed.',
    )


class RequiredDuringSchedulingIgnoredDuringExecutionItem(BaseModel):
    """
    Defines a set of pods (namely those matching the labelSelector
    relative to the given namespace(s)) that this pod should be
    co-located (affinity) or not co-located (anti-affinity) with,
    where co-located is defined as running on a node whose value of
    the label with key <topologyKey> matches that of any node on which
    a pod of the set of pods is running
    """

    labelSelector: Optional[LabelSelector1] = Field(
        None,
        description="A label query over a set of resources, in this case pods.\nIf it's null, this PodAffinityTerm matches with no Pods.",
    )
    matchLabelKeys: Optional[list[str]] = Field(
        None,
        description="MatchLabelKeys is a set of pod label keys to select which pods will\nbe taken into consideration. The keys are used to lookup values from the\nincoming pod labels, those key-value labels are merged with `labelSelector` as `key in (value)`\nto select the group of existing pods which pods will be taken into consideration\nfor the incoming pod's pod (anti) affinity. Keys that don't exist in the incoming\npod labels will be ignored. The default value is empty.\nThe same key is forbidden to exist in both matchLabelKeys and labelSelector.\nAlso, matchLabelKeys cannot be set when labelSelector isn't set.\nThis is a beta field and requires enabling MatchLabelKeysInPodAffinity feature gate (enabled by default).",
    )
    mismatchLabelKeys: Optional[list[str]] = Field(
        None,
        description="MismatchLabelKeys is a set of pod label keys to select which pods will\nbe taken into consideration. The keys are used to lookup values from the\nincoming pod labels, those key-value labels are merged with `labelSelector` as `key notin (value)`\nto select the group of existing pods which pods will be taken into consideration\nfor the incoming pod's pod (anti) affinity. Keys that don't exist in the incoming\npod labels will be ignored. The default value is empty.\nThe same key is forbidden to exist in both mismatchLabelKeys and labelSelector.\nAlso, mismatchLabelKeys cannot be set when labelSelector isn't set.\nThis is a beta field and requires enabling MatchLabelKeysInPodAffinity feature gate (enabled by default).",
    )
    namespaceSelector: Optional[NamespaceSelector1] = Field(
        None,
        description='A label query over the set of namespaces that the term applies to.\nThe term is applied to the union of the namespaces selected by this field\nand the ones listed in the namespaces field.\nnull selector and null or empty namespaces list means "this pod\'s namespace".\nAn empty selector ({}) matches all namespaces.',
    )
    namespaces: Optional[list[str]] = Field(
        None,
        description='namespaces specifies a static list of namespace names that the term applies to.\nThe term is applied to the union of the namespaces listed in this field\nand the ones selected by namespaceSelector.\nnull or empty namespaces list and null namespaceSelector means "this pod\'s namespace".',
    )
    topologyKey: str = Field(
        ...,
        description="This pod should be co-located (affinity) or not co-located (anti-affinity) with the pods matching\nthe labelSelector in the specified namespaces, where co-located is defined as running on a node\nwhose value of the label with key topologyKey matches that of any node on which any of the\nselected pods is running.\nEmpty topologyKey is not allowed.",
    )


class PodAffinity(BaseModel):
    """
    Pod affinity is a group of inter pod affinity scheduling rules.
    """

    preferredDuringSchedulingIgnoredDuringExecution: Optional[
        list[PreferredDuringSchedulingIgnoredDuringExecutionItem]
    ] = Field(
        None,
        description='The scheduler will prefer to schedule pods to nodes that satisfy\nthe affinity expressions specified by this field, but it may choose\na node that violates one or more of the expressions. The node that is\nmost preferred is the one with the greatest sum of weights, i.e.\nfor each node that meets all of the scheduling requirements (resource\nrequest, requiredDuringScheduling affinity expressions, etc.),\ncompute a sum by iterating through the elements of this field and adding\n"weight" to the sum if the node has pods which matches the corresponding podAffinityTerm; the\nnode(s) with the highest sum are the most preferred.',
    )
    requiredDuringSchedulingIgnoredDuringExecution: Optional[
        list[RequiredDuringSchedulingIgnoredDuringExecutionItem]
    ] = Field(
        None,
        description="If the affinity requirements specified by this field are not met at\nscheduling time, the pod will not be scheduled onto the node.\nIf the affinity requirements specified by this field cease to be met\nat some point during pod execution (e.g. due to a pod label update), the\nsystem may or may not try to eventually evict the pod from its node.\nWhen there are multiple elements, the lists of nodes corresponding to each\npodAffinityTerm are intersected, i.e. all terms must be satisfied.",
    )


class Proxy(BaseModel):
    """
    ProxySpec defines the proxy configuration for NIMService.
    """

    certConfigMap: Optional[str] = None
    httpProxy: Optional[str] = None
    httpsProxy: Optional[str] = None
    noProxy: Optional[str] = None


class HttpGet1(BaseModel):
    """
    HTTPGet specifies the http request to perform.
    """

    host: Optional[str] = Field(
        None,
        description='Host name to connect to, defaults to the pod IP. You probably want to set\n"Host" in httpHeaders instead.',
    )
    httpHeaders: Optional[list[HttpHeader]] = Field(
        None,
        description="Custom headers to set in the request. HTTP allows repeated headers.",
    )
    path: Optional[str] = Field(None, description="Path to access on the HTTP server.")
    port: Union[int, str] = Field(
        ...,
        description="Name or number of the port to access on the container.\nNumber must be in the range 1 to 65535.\nName must be an IANA_SVC_NAME.",
    )
    scheme: Optional[str] = Field(None, description="Scheme to use for connecting to the host.\nDefaults to HTTP.")


class Probe1(BaseModel):
    """
    Probe describes a health check to be performed against a container to determine whether it is
    alive or ready to receive traffic.
    """

    exec: Optional[Exec] = Field(None, description="Exec specifies the action to take.")
    failureThreshold: Optional[int] = Field(
        None,
        description="Minimum consecutive failures for the probe to be considered failed after having succeeded.\nDefaults to 3. Minimum value is 1.",
    )
    grpc: Optional[Grpc] = Field(None, description="GRPC specifies an action involving a GRPC port.")
    httpGet: Optional[HttpGet1] = Field(None, description="HTTPGet specifies the http request to perform.")
    initialDelaySeconds: Optional[int] = Field(
        None,
        description="Number of seconds after the container has started before liveness probes are initiated.\nMore info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes",
    )
    periodSeconds: Optional[int] = Field(
        None,
        description="How often (in seconds) to perform the probe.\nDefault to 10 seconds. Minimum value is 1.",
    )
    successThreshold: Optional[int] = Field(
        None,
        description="Minimum consecutive successes for the probe to be considered successful after having failed.\nDefaults to 1. Must be 1 for liveness and startup. Minimum value is 1.",
    )
    tcpSocket: Optional[TcpSocket] = Field(None, description="TCPSocket specifies an action involving a TCP port.")
    terminationGracePeriodSeconds: Optional[int] = Field(
        None,
        description="Optional duration in seconds the pod needs to terminate gracefully upon probe failure.\nThe grace period is the duration in seconds after the processes running in the pod are sent\na termination signal and the time when the processes are forcibly halted with a kill signal.\nSet this value longer than the expected cleanup time for your process.\nIf this value is nil, the pod's terminationGracePeriodSeconds will be used. Otherwise, this\nvalue overrides the value provided by the pod spec.\nValue must be non-negative integer. The value zero indicates stop immediately via\nthe kill signal (no opportunity to shut down).\nThis is a beta field and requires enabling ProbeTerminationGracePeriod feature gate.\nMinimum value is 1. spec.terminationGracePeriodSeconds is used if unset.",
    )
    timeoutSeconds: Optional[int] = Field(
        None,
        description="Number of seconds after which the probe times out.\nDefaults to 1 second. Minimum value is 1.\nMore info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes",
    )


class ReadinessProbe(BaseModel):
    """
    Probe defines attributes for startup/liveness/readiness probes.
    """

    enabled: Optional[bool] = None
    probe: Optional[Probe1] = Field(
        None,
        description="Probe describes a health check to be performed against a container to determine whether it is\nalive or ready to receive traffic.",
    )


class Claim(BaseModel):
    """
    ResourceClaim references one entry in PodSpec.ResourceClaims.
    """

    name: str = Field(
        ...,
        description="Name must match the name of one entry in pod.spec.resourceClaims of\nthe Pod where this field is used. It makes that resource available\ninside a container.",
    )
    request: Optional[str] = Field(
        None,
        description="Request is the name chosen for a request in the referenced claim.\nIf empty, everything from the claim is made available, otherwise\nonly the result of this request.",
    )


class Limits(RootModel[int]):
    root: int


class Limits1(RootModel[str]):
    root: str


class Requests(RootModel[int]):
    root: int


class Requests1(RootModel[str]):
    root: str


class Resources(BaseModel):
    """
    ResourceRequirements describes the compute resource requirements.
    """

    claims: Optional[list[Claim]] = Field(
        None,
        description="Claims lists the names of resources, defined in spec.resourceClaims,\nthat are used by this container.\n\nThis is an alpha field and requires enabling the\nDynamicResourceAllocation feature gate.\n\nThis field is immutable. It can only be set for containers.",
    )
    limits: Optional[dict[str, Union[Limits, Limits1]]] = Field(
        None,
        description="Limits describes the maximum amount of compute resources allowed.\nMore info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/",
    )
    requests: Optional[dict[str, Union[Requests, Requests1]]] = Field(
        None,
        description="Requests describes the minimum amount of compute resources required.\nIf Requests is omitted for a container, it defaults to Limits if that is explicitly specified,\notherwise to an implementation-defined value. Requests cannot exceed Limits.\nMore info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/",
    )


class Policy(BaseModel):
    """
    HPAScalingPolicy is a single policy which must hold true for a specified past interval.
    """

    periodSeconds: int = Field(
        ...,
        description="periodSeconds specifies the window of time for which the policy should hold true.\nPeriodSeconds must be greater than zero and less than or equal to 1800 (30 min).",
    )
    type: str = Field(..., description="type is used to specify the scaling policy.")
    value: int = Field(
        ...,
        description="value contains the amount of change which is permitted by the policy.\nIt must be greater than zero",
    )


class ScaleDown(BaseModel):
    """
    scaleDown is scaling policy for scaling Down.
    If not set, the default value is to allow to scale down to minReplicas pods, with a
    300 second stabilization window (i.e., the highest recommendation for
    the last 300sec is used).
    """

    policies: Optional[list[Policy]] = Field(
        None,
        description="policies is a list of potential scaling polices which can be used during scaling.\nAt least one policy must be specified, otherwise the HPAScalingRules will be discarded as invalid",
    )
    selectPolicy: Optional[str] = Field(
        None,
        description="selectPolicy is used to specify which policy should be used.\nIf not set, the default value Max is used.",
    )
    stabilizationWindowSeconds: Optional[int] = Field(
        None,
        description="stabilizationWindowSeconds is the number of seconds for which past recommendations should be\nconsidered while scaling up or scaling down.\nStabilizationWindowSeconds must be greater than or equal to zero and less than or equal to 3600 (one hour).\nIf not set, use the default values:\n- For scale up: 0 (i.e. no stabilization is done).\n- For scale down: 300 (i.e. the stabilization window is 300 seconds long).",
    )


class ScaleUp(BaseModel):
    """
    scaleUp is scaling policy for scaling Up.
    If not set, the default value is the higher of:
      * increase no more than 4 pods per 60 seconds
      * double the number of pods per 60 seconds
    No stabilization is used.
    """

    policies: Optional[list[Policy]] = Field(
        None,
        description="policies is a list of potential scaling polices which can be used during scaling.\nAt least one policy must be specified, otherwise the HPAScalingRules will be discarded as invalid",
    )
    selectPolicy: Optional[str] = Field(
        None,
        description="selectPolicy is used to specify which policy should be used.\nIf not set, the default value Max is used.",
    )
    stabilizationWindowSeconds: Optional[int] = Field(
        None,
        description="stabilizationWindowSeconds is the number of seconds for which past recommendations should be\nconsidered while scaling up or scaling down.\nStabilizationWindowSeconds must be greater than or equal to zero and less than or equal to 3600 (one hour).\nIf not set, use the default values:\n- For scale up: 0 (i.e. no stabilization is done).\n- For scale down: 300 (i.e. the stabilization window is 300 seconds long).",
    )


class Behavior(BaseModel):
    """
    HorizontalPodAutoscalerBehavior configures the scaling behavior of the target
    in both Up and Down directions (scaleUp and scaleDown fields respectively).
    """

    scaleDown: Optional[ScaleDown] = Field(
        None,
        description="scaleDown is scaling policy for scaling Down.\nIf not set, the default value is to allow to scale down to minReplicas pods, with a\n300 second stabilization window (i.e., the highest recommendation for\nthe last 300sec is used).",
    )
    scaleUp: Optional[ScaleUp] = Field(
        None,
        description="scaleUp is scaling policy for scaling Up.\nIf not set, the default value is the higher of:\n  * increase no more than 4 pods per 60 seconds\n  * double the number of pods per 60 seconds\nNo stabilization is used.",
    )


class AverageValue(RootModel[int]):
    root: int


class AverageValue1(RootModel[str]):
    root: str


class Value(RootModel[int]):
    root: int


class Value1(RootModel[str]):
    root: str


class Target(BaseModel):
    """
    target specifies the target value for the given metric
    """

    averageUtilization: Optional[int] = Field(
        None,
        description="averageUtilization is the target value of the average of the\nresource metric across all relevant pods, represented as a percentage of\nthe requested value of the resource for the pods.\nCurrently only valid for Resource metric source type",
    )
    averageValue: Optional[Union[AverageValue, AverageValue1]] = Field(
        None,
        description="averageValue is the target value of the average of the\nmetric across all relevant pods (as a quantity)",
    )
    type: str = Field(
        ...,
        description="type represents whether the metric type is Utilization, Value, or AverageValue",
    )
    value: Optional[Union[Value, Value1]] = Field(
        None, description="value is the target value of the metric (as a quantity)."
    )


class ContainerResource(BaseModel):
    """
    containerResource refers to a resource metric (such as those specified in
    requests and limits) known to Kubernetes describing a single container in
    each pod of the current scale target (e.g. CPU or memory). Such metrics are
    built in to Kubernetes, and have special scaling options on top of those
    available to normal per-pod metrics using the "pods" source.
    This is an alpha feature and can be enabled by the HPAContainerMetrics feature flag.
    """

    container: str = Field(
        ...,
        description="container is the name of the container in the pods of the scaling target",
    )
    name: str = Field(..., description="name is the name of the resource in question.")
    target: Target = Field(..., description="target specifies the target value for the given metric")


class Selector(BaseModel):
    """
    selector is the string-encoded form of a standard kubernetes label selector for the given metric
    When set, it is passed as an additional parameter to the metrics server for more specific metrics scoping.
    When unset, just the metricName will be used to gather metrics.
    """

    matchExpressions: Optional[list[MatchExpression]] = Field(
        None,
        description="matchExpressions is a list of label selector requirements. The requirements are ANDed.",
    )
    matchLabels: Optional[dict[str, str]] = Field(
        None,
        description='matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\nmap is equivalent to an element of matchExpressions, whose key field is "key", the\noperator is "In", and the values array contains only "value". The requirements are ANDed.',
    )


class Metric1(BaseModel):
    """
    metric identifies the target metric by name and selector
    """

    name: str = Field(..., description="name is the name of the given metric")
    selector: Optional[Selector] = Field(
        None,
        description="selector is the string-encoded form of a standard kubernetes label selector for the given metric\nWhen set, it is passed as an additional parameter to the metrics server for more specific metrics scoping.\nWhen unset, just the metricName will be used to gather metrics.",
    )


class AverageValue2(RootModel[int]):
    root: int


class AverageValue3(RootModel[str]):
    root: str


class Value2(RootModel[int]):
    root: int


class Value3(RootModel[str]):
    root: str


class Target1(BaseModel):
    """
    target specifies the target value for the given metric
    """

    averageUtilization: Optional[int] = Field(
        None,
        description="averageUtilization is the target value of the average of the\nresource metric across all relevant pods, represented as a percentage of\nthe requested value of the resource for the pods.\nCurrently only valid for Resource metric source type",
    )
    averageValue: Optional[Union[AverageValue2, AverageValue3]] = Field(
        None,
        description="averageValue is the target value of the average of the\nmetric across all relevant pods (as a quantity)",
    )
    type: str = Field(
        ...,
        description="type represents whether the metric type is Utilization, Value, or AverageValue",
    )
    value: Optional[Union[Value2, Value3]] = Field(
        None, description="value is the target value of the metric (as a quantity)."
    )


class External(BaseModel):
    """
    external refers to a global metric that is not associated
    with any Kubernetes object. It allows autoscaling based on information
    coming from components running outside of cluster
    (for example length of queue in cloud messaging service, or
    QPS from loadbalancer running outside of cluster).
    """

    metric: Metric1 = Field(..., description="metric identifies the target metric by name and selector")
    target: Target1 = Field(..., description="target specifies the target value for the given metric")


class DescribedObject(BaseModel):
    """
    describedObject specifies the descriptions of a object,such as kind,name apiVersion
    """

    apiVersion: Optional[str] = Field(None, description="apiVersion is the API version of the referent")
    kind: str = Field(
        ...,
        description="kind is the kind of the referent; More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
    )
    name: str = Field(
        ...,
        description="name is the name of the referent; More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names",
    )


class Selector1(BaseModel):
    """
    selector is the string-encoded form of a standard kubernetes label selector for the given metric
    When set, it is passed as an additional parameter to the metrics server for more specific metrics scoping.
    When unset, just the metricName will be used to gather metrics.
    """

    matchExpressions: Optional[list[MatchExpression]] = Field(
        None,
        description="matchExpressions is a list of label selector requirements. The requirements are ANDed.",
    )
    matchLabels: Optional[dict[str, str]] = Field(
        None,
        description='matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\nmap is equivalent to an element of matchExpressions, whose key field is "key", the\noperator is "In", and the values array contains only "value". The requirements are ANDed.',
    )


class Metric2(BaseModel):
    """
    metric identifies the target metric by name and selector
    """

    name: str = Field(..., description="name is the name of the given metric")
    selector: Optional[Selector1] = Field(
        None,
        description="selector is the string-encoded form of a standard kubernetes label selector for the given metric\nWhen set, it is passed as an additional parameter to the metrics server for more specific metrics scoping.\nWhen unset, just the metricName will be used to gather metrics.",
    )


class AverageValue4(RootModel[int]):
    root: int


class AverageValue5(RootModel[str]):
    root: str


class Value4(RootModel[int]):
    root: int


class Value5(RootModel[str]):
    root: str


class Target2(BaseModel):
    """
    target specifies the target value for the given metric
    """

    averageUtilization: Optional[int] = Field(
        None,
        description="averageUtilization is the target value of the average of the\nresource metric across all relevant pods, represented as a percentage of\nthe requested value of the resource for the pods.\nCurrently only valid for Resource metric source type",
    )
    averageValue: Optional[Union[AverageValue4, AverageValue5]] = Field(
        None,
        description="averageValue is the target value of the average of the\nmetric across all relevant pods (as a quantity)",
    )
    type: str = Field(
        ...,
        description="type represents whether the metric type is Utilization, Value, or AverageValue",
    )
    value: Optional[Union[Value4, Value5]] = Field(
        None, description="value is the target value of the metric (as a quantity)."
    )


class Object(BaseModel):
    """
    object refers to a metric describing a single kubernetes object
    (for example, hits-per-second on an Ingress object).
    """

    describedObject: DescribedObject = Field(
        ...,
        description="describedObject specifies the descriptions of a object,such as kind,name apiVersion",
    )
    metric: Metric2 = Field(..., description="metric identifies the target metric by name and selector")
    target: Target2 = Field(..., description="target specifies the target value for the given metric")


class Selector2(BaseModel):
    """
    selector is the string-encoded form of a standard kubernetes label selector for the given metric
    When set, it is passed as an additional parameter to the metrics server for more specific metrics scoping.
    When unset, just the metricName will be used to gather metrics.
    """

    matchExpressions: Optional[list[MatchExpression]] = Field(
        None,
        description="matchExpressions is a list of label selector requirements. The requirements are ANDed.",
    )
    matchLabels: Optional[dict[str, str]] = Field(
        None,
        description='matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\nmap is equivalent to an element of matchExpressions, whose key field is "key", the\noperator is "In", and the values array contains only "value". The requirements are ANDed.',
    )


class Metric3(BaseModel):
    """
    metric identifies the target metric by name and selector
    """

    name: str = Field(..., description="name is the name of the given metric")
    selector: Optional[Selector2] = Field(
        None,
        description="selector is the string-encoded form of a standard kubernetes label selector for the given metric\nWhen set, it is passed as an additional parameter to the metrics server for more specific metrics scoping.\nWhen unset, just the metricName will be used to gather metrics.",
    )


class AverageValue6(RootModel[int]):
    root: int


class AverageValue7(RootModel[str]):
    root: str


class Value6(RootModel[int]):
    root: int


class Value7(RootModel[str]):
    root: str


class Target3(BaseModel):
    """
    target specifies the target value for the given metric
    """

    averageUtilization: Optional[int] = Field(
        None,
        description="averageUtilization is the target value of the average of the\nresource metric across all relevant pods, represented as a percentage of\nthe requested value of the resource for the pods.\nCurrently only valid for Resource metric source type",
    )
    averageValue: Optional[Union[AverageValue6, AverageValue7]] = Field(
        None,
        description="averageValue is the target value of the average of the\nmetric across all relevant pods (as a quantity)",
    )
    type: str = Field(
        ...,
        description="type represents whether the metric type is Utilization, Value, or AverageValue",
    )
    value: Optional[Union[Value6, Value7]] = Field(
        None, description="value is the target value of the metric (as a quantity)."
    )


class Pods(BaseModel):
    """
    pods refers to a metric describing each pod in the current scale target
    (for example, transactions-processed-per-second).  The values will be
    averaged together before being compared to the target value.
    """

    metric: Metric3 = Field(..., description="metric identifies the target metric by name and selector")
    target: Target3 = Field(..., description="target specifies the target value for the given metric")


class AverageValue8(RootModel[int]):
    root: int


class AverageValue9(RootModel[str]):
    root: str


class Value8(RootModel[int]):
    root: int


class Value9(RootModel[str]):
    root: str


class Target4(BaseModel):
    """
    target specifies the target value for the given metric
    """

    averageUtilization: Optional[int] = Field(
        None,
        description="averageUtilization is the target value of the average of the\nresource metric across all relevant pods, represented as a percentage of\nthe requested value of the resource for the pods.\nCurrently only valid for Resource metric source type",
    )
    averageValue: Optional[Union[AverageValue8, AverageValue9]] = Field(
        None,
        description="averageValue is the target value of the average of the\nmetric across all relevant pods (as a quantity)",
    )
    type: str = Field(
        ...,
        description="type represents whether the metric type is Utilization, Value, or AverageValue",
    )
    value: Optional[Union[Value8, Value9]] = Field(
        None, description="value is the target value of the metric (as a quantity)."
    )


class Resource2(BaseModel):
    """
    resource refers to a resource metric (such as those specified in
    requests and limits) known to Kubernetes describing each pod in the
    current scale target (e.g. CPU or memory). Such metrics are built in to
    Kubernetes, and have special scaling options on top of those available
    to normal per-pod metrics using the "pods" source.
    """

    name: str = Field(..., description="name is the name of the resource in question.")
    target: Target4 = Field(..., description="target specifies the target value for the given metric")


class Metric(BaseModel):
    """
    MetricSpec specifies how to scale based on a single metric
    (only `type` and one other matching field should be set at once).
    """

    containerResource: Optional[ContainerResource] = Field(
        None,
        description='containerResource refers to a resource metric (such as those specified in\nrequests and limits) known to Kubernetes describing a single container in\neach pod of the current scale target (e.g. CPU or memory). Such metrics are\nbuilt in to Kubernetes, and have special scaling options on top of those\navailable to normal per-pod metrics using the "pods" source.\nThis is an alpha feature and can be enabled by the HPAContainerMetrics feature flag.',
    )
    external: Optional[External] = Field(
        None,
        description="external refers to a global metric that is not associated\nwith any Kubernetes object. It allows autoscaling based on information\ncoming from components running outside of cluster\n(for example length of queue in cloud messaging service, or\nQPS from loadbalancer running outside of cluster).",
    )
    object: Optional[Object] = Field(
        None,
        description="object refers to a metric describing a single kubernetes object\n(for example, hits-per-second on an Ingress object).",
    )
    pods: Optional[Pods] = Field(
        None,
        description="pods refers to a metric describing each pod in the current scale target\n(for example, transactions-processed-per-second).  The values will be\naveraged together before being compared to the target value.",
    )
    resource: Optional[Resource2] = Field(
        None,
        description='resource refers to a resource metric (such as those specified in\nrequests and limits) known to Kubernetes describing each pod in the\ncurrent scale target (e.g. CPU or memory). Such metrics are built in to\nKubernetes, and have special scaling options on top of those available\nto normal per-pod metrics using the "pods" source.',
    )
    type: str = Field(
        ...,
        description='type is the type of metric source.  It should be one of "ContainerResource", "External",\n"Object", "Pods" or "Resource", each mapping to a matching field in the object.\nNote: "ContainerResource" type is available on when the feature-gate\nHPAContainerMetrics is enabled',
    )


class Hpa(BaseModel):
    """
    HorizontalPodAutoscalerSpec defines the parameters required to setup HPA.
    """

    behavior: Optional[Behavior] = Field(
        None,
        description="HorizontalPodAutoscalerBehavior configures the scaling behavior of the target\nin both Up and Down directions (scaleUp and scaleDown fields respectively).",
    )
    maxReplicas: int
    metrics: Optional[list[Metric]] = None
    minReplicas: Optional[int] = None


class Scale(BaseModel):
    """
    Autoscaling defines attributes to automatically scale the service based on metrics.
    """

    annotations: Optional[dict[str, str]] = None
    enabled: Optional[bool] = None
    hpa: Optional[Hpa] = Field(
        None,
        description="HorizontalPodAutoscalerSpec defines the parameters required to setup HPA.",
    )


class HttpGet2(BaseModel):
    """
    HTTPGet specifies the http request to perform.
    """

    host: Optional[str] = Field(
        None,
        description='Host name to connect to, defaults to the pod IP. You probably want to set\n"Host" in httpHeaders instead.',
    )
    httpHeaders: Optional[list[HttpHeader]] = Field(
        None,
        description="Custom headers to set in the request. HTTP allows repeated headers.",
    )
    path: Optional[str] = Field(None, description="Path to access on the HTTP server.")
    port: Union[int, str] = Field(
        ...,
        description="Name or number of the port to access on the container.\nNumber must be in the range 1 to 65535.\nName must be an IANA_SVC_NAME.",
    )
    scheme: Optional[str] = Field(None, description="Scheme to use for connecting to the host.\nDefaults to HTTP.")


class Probe2(BaseModel):
    """
    Probe describes a health check to be performed against a container to determine whether it is
    alive or ready to receive traffic.
    """

    exec: Optional[Exec] = Field(None, description="Exec specifies the action to take.")
    failureThreshold: Optional[int] = Field(
        None,
        description="Minimum consecutive failures for the probe to be considered failed after having succeeded.\nDefaults to 3. Minimum value is 1.",
    )
    grpc: Optional[Grpc] = Field(None, description="GRPC specifies an action involving a GRPC port.")
    httpGet: Optional[HttpGet2] = Field(None, description="HTTPGet specifies the http request to perform.")
    initialDelaySeconds: Optional[int] = Field(
        None,
        description="Number of seconds after the container has started before liveness probes are initiated.\nMore info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes",
    )
    periodSeconds: Optional[int] = Field(
        None,
        description="How often (in seconds) to perform the probe.\nDefault to 10 seconds. Minimum value is 1.",
    )
    successThreshold: Optional[int] = Field(
        None,
        description="Minimum consecutive successes for the probe to be considered successful after having failed.\nDefaults to 1. Must be 1 for liveness and startup. Minimum value is 1.",
    )
    tcpSocket: Optional[TcpSocket] = Field(None, description="TCPSocket specifies an action involving a TCP port.")
    terminationGracePeriodSeconds: Optional[int] = Field(
        None,
        description="Optional duration in seconds the pod needs to terminate gracefully upon probe failure.\nThe grace period is the duration in seconds after the processes running in the pod are sent\na termination signal and the time when the processes are forcibly halted with a kill signal.\nSet this value longer than the expected cleanup time for your process.\nIf this value is nil, the pod's terminationGracePeriodSeconds will be used. Otherwise, this\nvalue overrides the value provided by the pod spec.\nValue must be non-negative integer. The value zero indicates stop immediately via\nthe kill signal (no opportunity to shut down).\nThis is a beta field and requires enabling ProbeTerminationGracePeriod feature gate.\nMinimum value is 1. spec.terminationGracePeriodSeconds is used if unset.",
    )
    timeoutSeconds: Optional[int] = Field(
        None,
        description="Number of seconds after which the probe times out.\nDefaults to 1 second. Minimum value is 1.\nMore info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes",
    )


class StartupProbe(BaseModel):
    """
    Probe defines attributes for startup/liveness/readiness probes.
    """

    enabled: Optional[bool] = None
    probe: Optional[Probe2] = Field(
        None,
        description="Probe describes a health check to be performed against a container to determine whether it is\nalive or ready to receive traffic.",
    )


class NimCache(BaseModel):
    """
    NIMCacheVolSpec defines the spec to use NIMCache volume.
    """

    name: Optional[str] = None
    profile: Optional[str] = None


class Pvc(BaseModel):
    """
    PersistentVolumeClaim is the pvc volume used for caching NIM
    """

    annotations: Optional[dict[str, str]] = Field(None, description="Annotations for the PVC")
    create: Optional[bool] = Field(
        None,
        description="Create specifies whether to create a new PersistentVolumeClaim (PVC).\nIf set to false, an existing PVC must be referenced via the `Name` field.",
    )
    name: Optional[str] = Field(
        None,
        description="Name of the PVC to use. Required if `Create` is false (i.e., using an existing PVC).",
    )
    size: Optional[str] = Field(None, description="Size of the NIM cache in Gi, used during PVC creation")
    storageClass: Optional[str] = Field(
        None,
        description="StorageClass to be used for PVC creation. Leave it as empty if the PVC is already created or\na default storage class is set in the cluster.",
    )
    subPath: Optional[str] = Field(None, description="SubPath is the path inside the PVC that should be mounted")
    volumeAccessMode: Optional[str] = Field(None, description="VolumeAccessMode is the volume access mode of the PVC")


class SharedMemorySizeLimit(RootModel[int]):
    root: int


class SharedMemorySizeLimit1(RootModel[str]):
    root: str


class Storage(BaseModel):
    """
    Storage is the target storage for caching NIM model if NIMCache is not provided
    """

    hostPath: Optional[str] = Field(None, description="HostPath is the host path volume for caching NIM")
    nimCache: Optional[NimCache] = Field(None, description="NIMCacheVolSpec defines the spec to use NIMCache volume.")
    pvc: Optional[Pvc] = Field(None, description="PersistentVolumeClaim is the pvc volume used for caching NIM")
    readOnly: Optional[bool] = Field(
        None,
        description="ReadOnly mode indicates if the volume should be mounted as read-only",
    )
    sharedMemorySizeLimit: Optional[Union[SharedMemorySizeLimit, SharedMemorySizeLimit1]] = Field(
        None,
        description="SharedMemorySizeLimit sets the max size of the shared memory volume (emptyDir) used by NIMs for fast model runtime I/O.",
    )


class Toleration(BaseModel):
    """
    The pod this Toleration is attached to tolerates any taint that matches
    the triple <key,value,effect> using the matching operator <operator>.
    """

    effect: Optional[str] = Field(
        None,
        description="Effect indicates the taint effect to match. Empty means match all taint effects.\nWhen specified, allowed values are NoSchedule, PreferNoSchedule and NoExecute.",
    )
    key: Optional[str] = Field(
        None,
        description="Key is the taint key that the toleration applies to. Empty means match all taint keys.\nIf the key is empty, operator must be Exists; this combination means to match all values and all keys.",
    )
    operator: Optional[str] = Field(
        None,
        description="Operator represents a key's relationship to the value.\nValid operators are Exists and Equal. Defaults to Equal.\nExists is equivalent to wildcard for value, so that a pod can\ntolerate all taints of a particular category.",
    )
    tolerationSeconds: Optional[int] = Field(
        None,
        description="TolerationSeconds represents the period of time the toleration (which must be\nof effect NoExecute, otherwise this field is ignored) tolerates the taint. By default,\nit is not set, which means tolerate the taint forever (do not evict). Zero and\nnegative values will be treated as 0 (evict immediately) by the system.",
    )
    value: Optional[str] = Field(
        None,
        description="Value is the taint value the toleration matches to.\nIf the operator is Exists, the value should be empty, otherwise just a regular string.",
    )


class Spec(BaseModel):
    """
    NIMServiceSpec defines the desired state of NIMService.
    """

    annotations: Optional[dict[str, str]] = None
    args: Optional[list[str]] = None
    authSecret: str = Field(
        ...,
        description="The name of an existing pull secret containing the NGC_API_KEY",
    )
    command: Optional[list[str]] = None
    env: Optional[list[EnvItem]] = None
    expose: Optional[Expose] = Field(None, description="Expose defines attributes to expose the service.")
    groupID: Optional[int] = None
    image: Image = Field(..., description="Image defines image attributes.")
    labels: Optional[dict[str, str]] = None
    livenessProbe: Optional[LivenessProbe] = Field(
        None,
        description="Probe defines attributes for startup/liveness/readiness probes.",
    )
    metrics: Optional[Metrics] = Field(None, description="Metrics defines attributes to setup metrics collection.")
    nodeSelector: Optional[dict[str, str]] = None
    podAffinity: Optional[PodAffinity] = Field(
        None,
        description="Pod affinity is a group of inter pod affinity scheduling rules.",
    )
    proxy: Optional[Proxy] = Field(None, description="ProxySpec defines the proxy configuration for NIMService.")
    readinessProbe: Optional[ReadinessProbe] = Field(
        None,
        description="Probe defines attributes for startup/liveness/readiness probes.",
    )
    replicas: Optional[int] = Field(1, ge=1)
    resources: Optional[Resources] = Field(
        None,
        description="ResourceRequirements describes the compute resource requirements.",
    )
    runtimeClassName: Optional[str] = None
    scale: Optional[Scale] = Field(
        None,
        description="Autoscaling defines attributes to automatically scale the service based on metrics.",
    )
    schedulerName: Optional[str] = None
    startupProbe: Optional[StartupProbe] = Field(
        None,
        description="Probe defines attributes for startup/liveness/readiness probes.",
    )
    storage: Optional[Storage] = Field(
        None,
        description="Storage is the target storage for caching NIM model if NIMCache is not provided",
    )
    tolerations: Optional[list[Toleration]] = None
    userID: Optional[int] = None

    initContainers: Optional[list[ContainerSpec]] = Field(None, description="Init containers to add to the NimService")

    sidecarContainers: Optional[list[ContainerSpec]] = Field(
        None, description="Sidecar containers to add to the NimService"
    )


class ContainerSpec(BaseModel):
    """
    ContainerSpec defines a container specification for init or sidecar containers.
    """

    name: str = Field(..., description="Name of the container")
    image: Image = Field(..., description="Image defines image attributes.")
    command: Optional[list[str]] = Field(None, description="Command to execute in the container")
    args: Optional[list[str]] = Field(None, description="Arguments to pass to the command")
    env: Optional[list[EnvItem]] = Field(None, description="Environment variables for the container")
    workingDir: Optional[str] = Field(None, description="Working directory for the container")


class Status1(Enum):
    """
    status of the condition, one of True, False, Unknown.
    """

    True_ = "True"
    False_ = "False"
    Unknown = "Unknown"


class Condition(BaseModel):
    """
    Condition contains details for one aspect of the current state of this API Resource.
    """

    lastTransitionTime: AwareDatetime = Field(
        ...,
        description="lastTransitionTime is the last time the condition transitioned from one status to another.\nThis should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.",
    )
    message: str = Field(
        ...,
        description="message is a human readable message indicating details about the transition.\nThis may be an empty string.",
        max_length=32768,
    )
    observedGeneration: Optional[int] = Field(
        None,
        description="observedGeneration represents the .metadata.generation that the condition was set based upon.\nFor instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date\nwith respect to the current state of the instance.",
        ge=0,
    )
    reason: str = Field(
        ...,
        description="reason contains a programmatic identifier indicating the reason for the condition's last transition.\nProducers of specific condition types may define expected values and meanings for this field,\nand whether the values are considered a guaranteed API.\nThe value should be a CamelCase string.\nThis field may not be empty.",
        max_length=1024,
        min_length=1,
        pattern="^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$",
    )
    status: Status1 = Field(..., description="status of the condition, one of True, False, Unknown.")
    type: str = Field(
        ...,
        description="type of condition in CamelCase or in foo.example.com/CamelCase.",
        max_length=316,
        pattern="^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$",
    )


class Model(BaseModel):
    """
    ModelStatus defines the configuration of the NIMService model.
    """

    clusterEndpoint: str
    externalEndpoint: str
    name: str


class Status(BaseModel):
    """
    NIMServiceStatus defines the observed state of NIMService.
    """

    availableReplicas: Optional[int] = None
    conditions: Optional[list[Condition]] = None
    model: Optional[Model] = Field(
        None,
        description="ModelStatus defines the configuration of the NIMService model.",
    )
    state: Optional[str] = None


class NIMService(BaseModel):
    """
    NIMService is the Schema for the nimservices API.
    """

    apiVersion: Optional[str] = Field(
        None,
        description="APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
    )
    kind: Optional[str] = Field(
        None,
        description="Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
    )
    metadata: Optional[dict[str, Any]] = None
    spec: Optional[Spec] = Field(None, description="NIMServiceSpec defines the desired state of NIMService.")
    status: Optional[Status] = Field(None, description="NIMServiceStatus defines the observed state of NIMService.")
