# TODO(v2): This should no longer be needed after the migration.
version: "3.8"

services:
  postgres-db-migration:
    image: evaluator-build:local
    command:
      - "/bin/sh"
      - "-c"
      - "alembic revision --autogenerate -m '${UPGRADE}'"

    volumes:
      - ./alembic:/app/services/evaluator/alembic

    environment:
      - MODE=development
      - POSTGRES_URI=postgresql://nemo:nemo@postgres:5432/evaluation

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.9
    restart: always
    environment:
      - POSTGRES_USER=nemo
      - POSTGRES_PASSWORD=nemo
      - POSTGRES_DB=evaluation
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U nemo -d evaluation'"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
