# Example configuration for the Evaluator service
# Set NMP_CONFIG_FILE_PATH to this file path to use it

# Common service settings
service:
  log_format: plain # Use 'plain' for local dev, 'json' for production
  log_level: INFO
  host: "127.0.0.1"
  port: 8080

# Platform-wide settings
platform:
  base_url: "http://127.0.0.1:8080"
  entitystore_url: "http://127.0.0.1:8080"
  secrets_url: "http://127.0.0.1:8080"
  files_url: "http://127.0.0.1:8080"
  jobs_url: "http://127.0.0.1:8080"
  models_url: "http://127.0.0.1:8080"
  image_registry: "my-registry"
  image_tag: "local"

# Authorization settings
auth:
  enabled: false

# Entity Store service settings
entities:
  backend: memory

evaluator:
  recreate_existing_system_entities: True

# Jobs service settings
jobs:
  executor_defaults:
    docker:
      cleanup_completed_jobs_immediately: false
      # Path to the jobs-launcher binary for log forwarding
      launcher_tool_path: ./services/core/jobs/jobs-launcher/jobs-launcher

# Secrets service configuration - uses a secret key for encryption
secrets:
  encryption:
    current_provider: local_v1
    providers:
      secret_key:
        local_v1:
          value: "f4NPSp39YN5oWTwZ3iDX/L3PTvEH8qFvUs1noC/jWuo="

# Files service settings
files:
  default_storage_config:
    type: local
    path: ~/.local/share/nemo/files
