name: Validate PR title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

defaults:
  run:
    shell: bash -x -e -u -o pipefail {0}

permissions:
  pull-requests: read

jobs:
  semantic-pull-request:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Semantic PR Title
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1

      - name: PR Title length
        if: always()
        run: |
          title_length="$(jq -er '.pull_request.title | strings | length' "${GITHUB_EVENT_PATH}")"

          test "${title_length}" -le 100
