apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: frontend
requires:
  # local deployment "skaffold dev -p local"
  - path: skaffold/local.skaffold.yaml
  # local deployment "skaffold dev -p local-ingress"
  - path: skaffold/local-ingress.skaffold.yaml
  # ephemeral deploy profile "skaffold dev -p studio-ui-ephemeral"
  - path: skaffold/studio-ui-ephemeral.skaffold.yaml
  # tracks `main` in nemo-dev "skaffold dev -p dev"
  - path: skaffold/dev.skaffold.yaml
